#!/bin/bash

# altera-exec
# - written by azman@my1matrix.net
# - start quartus or altera-env shell

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
# look for config file
for conffile in "$(pwd)/.$MY1TOOL" "$HOME/.$MY1TOOL"; do
	[ ! -f $conffile ] && continue
	source $conffile ; break
done

ALTERA_VERS=${ALTERA_VERS:="13.0sp1"}
ALTERA_ROOT=${ALTERA_ROOT:="/home/share/appx/altera-${ALTERA_VERS}"}
ARCH_BITS="32"
BIN_TYPE=`file -L /bin/bash`
if [ "$(echo $BIN_TYPE | grep 'ELF 32-bit LSB executable')" == "" ] ; then
	ARCH_BITS="64"
fi
ALTERA_ARCH=${ALTERA_ARCH:="$ARCH_BITS"}
ALTERA_PATH=${ALTERA_ROOT}/quartus/bin
MODSIM_PATH=${ALTERA_ROOT}/modelsim_ase/bin

[ ! -d $ALTERA_PATH ] && echo "Cannot find path $ALTERA_PATH!"
[ ! -d $MODSIM_PATH ] && echo "Cannot find path $MODSIM_PATH!"

export PATH=$ALTERA_PATH:$MODSIM_PATH:$PATH

# added to allow modelsim binary to run
#LIB32_PATH="${ALTERA_ROOT}/lib32"
#[ -d "$LIB32_PATH" ] && export LD_LIBRARY_PATH="$LIB32_PATH"

if [ "$1" == "" ] ; then
	# start a shell
	exec env PS1="(ALTERA-EXEC) \u@\h:\w$ " $(which bash)
else
	target=$1
	shift
	[ "$target" == "sch" ] && quartus $@
	[ "$target" == "sim" ] && vsim $@
fi

exit 0
