#!/bin/bash

# check input
IFILE="$1"
[ -z "$IFILE" ] && exit 0
[ ! -f "$IFILE" ] &&
	echo -ne "\n[ABORT] Input file missing ($IFILE)!\n\n" && exit 0

# must have ffmpeg
DPROG="ffmpeg"
DEXEC=`which $DPROG 2>/dev/null`
[ ! -x "$DEXEC" ] && echo "Cannot exec $DPROG! Aborting!" && exit 1

audio_prepare_output()
{
	local ainp=$1
	local aout=$2
	[ -z "$aout" ] && aout="${ainp%.*}_conv.mp3"
	echo -n $aout
}

audio_docheck_output()
{
	local aout=$1
	[ -f "$aout" ] &&
		echo -ne "\n[ABORT] Output file exists ($aout)!\n\n" && exit 0
}

audio_get_volume()
{
	local isnd=$1
	local iopt=$2
	# audio options
	local aopt="-filter:a volumedetect"
	# check volume
	echo "Current volume for ${isnd}:"
	local tell=`${DEXEC} -i ${isnd} ${aopt} -f null /dev/null 2>&1`
	if [ -z "$iopt" -o "$iopt" != "--min" ] ; then
		echo "$tell" | grep volumedetect
	else
		echo "$tell" | grep volumedetect | grep "_volume:"
	fi
}

audio_normalize()
{
	local isnd=$1 ; shift
	local osnd=`audio_prepare_output $isnd`
	audio_docheck_output $osnd
	# audio options
	local aopt="-filter:a loudnorm"
	echo "Input: $isnd"
	echo "Output: $osnd"
	# do that thing you do...
	echo -n "Mixing volume (normalize)... "
	${DEXEC} -i ${isnd} ${aopt} ${osnd} 2>/dev/null
	[ $? -eq 0 ] && echo "done." || echo "error?!"
}

audio_gain()
{
	local isnd=$1 ; shift
	local osnd=`audio_prepare_output $isnd`
	audio_docheck_output $osnd
	# default gain
	local gain="5dB"
	while [ "$1" != "" ]; do
		case $1 in
			--gain) shift ; gain=$1 ;;
			*) echo -ne "\n[ABORT] Unknown param '$1'!\n\n" && exit 0
		esac
		shift
	done
	# audio options
	local aopt="-filter:a volume=${gain}"
	echo "Input: $isnd"
	echo "Output: $osnd"
	# do that thing you do...
	echo -n "Mixing volume (gain:${gain})... "
	${DEXEC} -i ${isnd} ${aopt} ${osnd} 2>/dev/null
	[ $? -eq 0 ] && echo "done." || echo "error?!"
}

audio_cut()
{
	local isnd=$1 ; shift
	local osnd=`audio_prepare_output $isnd`
	audio_docheck_output $osnd
	# default audio length is 1 minute
	local achk alen="1:00"
	while [ "$1" != "" ]; do
		case $1 in
			--alen) shift ; alen=$1 ;;
			--init) shift ; achk=$1 ;;
			*) echo -ne "\n[ABORT] Unknown param '$1'!\n\n" && exit 0
		esac
		shift
	done
	[ ! -z "$achk" ] && achk="-ss $achk"
	alen="-t $alen"
	# audio options
	local aopt="-c:a libmp3lame -ar 48000 -ab 128k"
	echo "Input: $isnd"
	echo "Output: $osnd"
	echo -n "Extracting audio {init:$achk,alen:$alen}..."
	${DEXEC} $achk -i $isnd $alen -vn $aopt $osnd >/dev/null 2>&1
	[ $? -eq 0 ] && echo "done." || echo "error?"
}

ATASK="$2" ; shift ; shift
[ -z "$ATASK" ] &&  ATASK=volume
case $ATASK in
	cut) audio_cut $IFILE $@ ;;
	volume) audio_get_volume $IFILE;;
	vol-gain) audio_get_volume $IFILE --min ; audio_gain $IFILE $@ ;;
	vol-norm) audio_get_volume $IFILE --min ; audio_normalize $IFILE $@ ;;
	*) echo "Unknown option '$ATASK'!" ;;
esac
