#!/bin/bash

# bash-setup
# - written by azman@my1matrix.org
# - create useful bash config files

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(cd $(dirname $0);pwd)"

MY1_BASH_PROFILE=$(cat <<SETVAR1
# ~/.bash_profile - login shells

umask 0022

add_path()
{
	local that=$1
	[ -d "\$that" ] && export PATH=\$PATH:\$that
}

add_path /usr/sbin
add_path /sbin
add_path $MY1PATH
add_path \$HOME/.local/bin

[ -f ~/.bashrc ] && source ~/.bashrc
[ -n "\$SSH_CLIENT" ] && export PS1="(SSH) \$PS1"
[ "\$(echo \$SSH_CLIENT | grep '127.0.0.1')" != "" ] && export DISPLAY=:0.0
SETVAR1
)
MY1_FILE_BASH_PROFILE=".bash_profile"

MY1_BASHRC=$(cat <<SETVAR2
# ~/.bashrc: non-login shells

export PS1="\\u@\\h:\\w\$ "
export VISUAL="\$(which vim 2>/dev/null)"
export HISTIGNORE="&:[bf]g:exit:[ ]*"
export LS_OPTIONS="-F -b -T 0 --color=auto"

alias ls='ls \$LS_OPTIONS'

#[ "\$SSH_CONNECTION" ] && [ -z "\$STY" ] && exec screen -d -R -S ssh
SETVAR2
)
MY1_FILE_BASHRC=".bashrc"

MY1_BASH_LOGOUT=$(cat <<SETVAR3
# ~/.bash_logout - logout script
clear
SETVAR3
)
MY1_FILE_BASH_LOGOUT=".bash_logout"

CHK_PATH="$HOME"
GO_WRITE=""
while [ "$1" != "" ]; do
	case $1 in
		--write) GO_WRITE=$1; ;;
		--path) shift
			[ ! -d $1 ] && echo "Invalid path '$1'!" && exit 1
			CHK_PATH=`cd $1 ; pwd`
			;;
		*) echo "Unknown parameter '$1'!" && exit 1 ;;
	esac
	shift
done

echo
if [ "$GO_WRITE" == "--write" ]; then
	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASH_PROFILE..."
	echo "$MY1_BASH_PROFILE" >$CHK_PATH/$MY1_FILE_BASH_PROFILE
	echo "done."
	echo
	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASHRC..."
	echo "$MY1_BASHRC" >$CHK_PATH/$MY1_FILE_BASHRC
	echo "done."
	echo
	echo -n "Writing to $CHK_PATH/$MY1_FILE_BASH_LOGOUT..."
	echo "$MY1_BASH_LOGOUT" >$CHK_PATH/$MY1_FILE_BASH_LOGOUT
	echo "done."
else
	echo "-------------"
	echo "BASH_PROFILE: ($CHK_PATH/$MY1_FILE_BASH_PROFILE)"
	echo "-------------"
	echo "$MY1_BASH_PROFILE"
	echo
	echo "-------"
	echo "BASHRC: ($CHK_PATH/$MY1_FILE_BASHRC)"
	echo "-------"
	echo "$MY1_BASHRC"
	echo
	echo "------------"
	echo "BASH_LOGOUT: ($CHK_PATH/$MY1_FILE_BASH_LOGOUT)"
	echo "------------"
	echo "$MY1_BASH_LOGOUT"
fi
echo

exit 0
