#!/bin/bash

# bash-setup
# - written by azman@my1matrix.net
# - create useful bash config files

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(cd $(dirname $0);pwd)"

MY1_BASH_PROFILE=$(cat <<SETVAR1
# ~/.bash_profile - login shells

umask 0022
export PATH=$MY1PATH:\$PATH:/usr/sbin:/sbin:\$HOME/slackware/slackbin

[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -n "\$SSH_CLIENT" ]] && export PS1="(SSH) \$PS1"
[[ "\$(echo \$SSH_CLIENT | grep '127.0.0.1')" != "" ]] && export DISPLAY=:0.0
SETVAR1
)
MY1_FILE_BASH_PROFILE="$HOME/.bash_profile"

MY1_BASHRC=$(cat <<SETVAR2
# ~/.bashrc: non-login shells

MY1PROMPT="\u@\h:\w$ "
[[ "\$PS1" =~ "\$MY1PROMPT" ]] || export PS1="\$MY1PROMPT"

export VISUAL="\$(which vim)"
export HISTIGNORE="&:[bf]g:exit:[ ]*"
export LS_OPTIONS="-F -b -T 0 --color=auto"

alias ls='ls \$LS_OPTIONS'

#[[ "\$SSH_CONNECTION" ]] && [[ -z "\$STY" ]] && exec screen -d -R -S ssh
SETVAR2
)
MY1_FILE_BASHRC="$HOME/.bashrc"

MY1_BASH_LOGOUT=$(cat <<SETVAR3
# ~/.bash_logout - logout script
clear
SETVAR3
)
MY1_FILE_BASH_LOGOUT="$HOME/.bash_logout"

GO_WRITE=""
while [[ "$1" != "" ]]; do
	case $1 in
		--write)
			GO_WRITE=$1;
			;;
		*)
			echo "Unknown PARAMETER ($1)!" && exit 1
			;;
	esac
	shift
done

echo
if [[ "$GO_WRITE" == "--write" ]] ; then
	echo -n "Writing to $MY1_FILE_BASH_PROFILE..."
	echo "$MY1_BASH_PROFILE" >$MY1_FILE_BASH_PROFILE
	echo "done."
else
	echo "-------------"
	echo "BASH_PROFILE:"
	echo "-------------"
	echo "$MY1_BASH_PROFILE"
fi
echo
if [[ "$GO_WRITE" == "--write" ]] ; then
	echo -n "Writing to $MY1_FILE_BASHRC..."
	echo "$MY1_BASHRC" >$MY1_FILE_BASHRC
	echo "done."
else
	echo "-------"
	echo "BASHRC:"
	echo "-------"
	echo "$MY1_BASHRC"
fi
echo
if [[ "$GO_WRITE" == "--write" ]] ; then
	echo -n "Writing to $MY1_FILE_BASH_LOGOUT..."
	echo "$MY1_BASH_LOGOUT" >$MY1_FILE_BASH_LOGOUT
	echo "done."
else
	echo "------------"
	echo "BASH_LOGOUT:"
	echo "------------"
	echo "$MY1_BASH_LOGOUT"
fi
echo

exit 0
