#!/bin/bash

# chkbattery
# - written by azman@my1matrix.net
# - simple script to check battery from /proc/acpi

ACPI_PATH="/proc/acpi/battery"
BATT_MISS="YES"

if [ -d ${ACPI_PATH}/BAT0 ] ; then
	TEST_BATT=$(cat ${ACPI_PATH}/BAT0/state | grep "present:")
	TEST_BATT=${TEST_BATT##*  }
	TEST_BATT=${TEST_BATT% *}
	[ "$TEST_BATT" != "no" ] && BATT_MISS="NO"
fi

if [ "$BATT_MISS" == "NO" ] ; then
	FULL_BATT=$(cat ${ACPI_PATH}/BAT0/info | grep "design capacity:")
	FULL_BATT=${FULL_BATT##*  }
	FULL_BATT=${FULL_BATT% *}
	PREV_BATT=$(cat ${ACPI_PATH}/BAT0/info | grep "last full capacity:")
	PREV_BATT=${PREV_BATT##*  }
	PREV_BATT=${PREV_BATT% *}
	CURR_BATT=$(cat ${ACPI_PATH}/BAT0/state | grep "remaining capacity:")
	CURR_BATT=${CURR_BATT##*  }
	CURR_BATT=${CURR_BATT% *}
	((CURR_PCTG=${CURR_BATT}*100/${PREV_BATT}))
	_CHARGING=$(cat ${ACPI_PATH}/BAT0/state | grep "charging state:")
	_CHARGING=${_CHARGING##*  }
	if [ "$_CHARGING" == "discharging" ] ; then
		LESS_BATT=$(cat ${ACPI_PATH}/BAT0/state | grep "present rate:")
		LESS_BATT=${LESS_BATT##*  }
		LESS_BATT=${LESS_BATT% *}
		((TIME1PART=${CURR_BATT}/${LESS_BATT}))
		if [ $TIME1PART -ne 0 ] ; then
			((TIME2PART=${CURR_BATT}-${TIME1PART}*${LESS_BATT}))
			TIME2LIVE="${TIME1PART}H"
		else
			TIME2PART=${CURR_BATT}
			TIME2LIVE=""
		fi
		((TIME2PART=${TIME2PART}*60/${LESS_BATT}))
		TIME2LIVE="${TIME2LIVE}${TIME2PART}M"
		CHK_STATE="$CURR_PCTG%-- ($TIME2LIVE)"
		_CHARGING="${TIME2LIVE}"
	elif [ "$_CHARGING" == "charging" ] ; then
		CHK_STATE="$CURR_PCTG%++"
	elif [ "$_CHARGING" == "charged" ] ; then
		CHK_STATE="$CURR_PCTG%##"
	else
		CHK_STATE="$CURR_PCTG%??"
	fi
else
	CURR_BATT="0"
	FULL_BATT="0"
	PREV_BATT="0"
	CURR_PCTG="100"
	_CHARGING="No battery!"
	CHK_STATE="AC"
fi

[ "$1" == "--state" ] && echo "$CHK_STATE" && exit 0

echo "$CURR_PCTG% <$_CHARGING> CURR=$CURR_BATT FULL=$FULL_BATT PREV=$PREV_BATT"

exit 0
