#!/bin/bash

# chkberg
# - written by azman@my1matrix.org
# - look up all repo on codeber belonging to a user account
# - clone if not already locally available

TOOL_NAME=`basename $0`
TOOL_PATH=`dirname $0`
CURR_PATH=`pwd`

THAT_NAME=curl
THAT_EXEC=$(which $THAT_NAME 2>/dev/null)
[ ! -x "$THAT_EXEC" ] &&
	echo "** Cannot find ${TOOL_NAME}!" && exit 1

# look for config file
for conf in "$CURR_PATH/.$TOOL_NAME" "$HOME/.$TOOL_NAME" ; do
	[ -f $conf ] &&  . $conf && break
done

USER_NAME=${USER_NAME:=""}
KEEP_LIST=${KEEP_LIST:="/tmp/list.txt"}
MAIN_URL=${MAIN_URL:="git@codeberg.org:"}
HTTP_URL=${HTTP_URL:="https://codeberg.org/"}
DO_CLONE=""
DO_QUIET="YES"
DO_CHECK=0

while [ "$1" != "" ] ; do
	case $1 in
		--clone|--exec|-x) DO_CLONE="YES" ;;
		--list) shift ; KEEP_LIST=$1 ;;
		--user) shift ; USER_NAME="$1" ;;
		--verbose|-v) DO_QUIET="NO" ;;
		--https) MAIN_URL="$HTTP_URL" ;;
		*) echo "Unknown parameter ($1)!" && exit 1 ;;
	esac
	shift
done

[ "$USER_NAME" == "" ] &&
	echo "Missing user info... abort!" && exit 1
echo -n "" >$KEEP_LIST
USRS_URL="https://codeberg.org/api/v1/users/$USER_NAME/repos"
THAT_OPTS="--request GET --url $USRS_URL"
CHK_LIST=$($THAT_EXEC $THAT_OPTS 2>/dev/null | grep -Po '"ssh_url":.*?[^\\]",')
echo "$CHK_LIST" | sed 's/^.*:\"\(.*\)\".*$/\1/' >>$KEEP_LIST

echo -n "Repository list saved "
REPO_CNT=`cat $KEEP_LIST | wc -l`
echo "in '$KEEP_LIST' ($REPO_CNT)."

for a in `cat $KEEP_LIST` ; do
	b=$(basename $a)
	if [ -d "$b" ] ; then
		[ "$DO_QUIET" = "NO" ] && echo "Repo '$b' => found."
		continue
	fi
	[ "$DO_CLONE" != "YES" ] &&
		echo "Repo '$b' => no local copy." && DO_CHECK=1 && continue
	echo "Cloning '$b'... "
	git clone ${MAIN_URL}${a}.git
done

[ $DO_CHECK -eq 0 ] && echo "Found local copies for ALL repo ($REPO_CNT)."

exit 0
