#!/bin/bash

SRC_PATH=$1
TGT_PATH=$2
CHK_EXEC=$3

[ ! -d "${SRC_PATH}" ] && echo "Invalid source path '${SRC_PATH}'!" && exit 1
[ ! -d "${TGT_PATH}" ] && echo "Invalid target path '${TGT_PATH}'!" && exit 1

SRC_PATH=`cd ${SRC_PATH} ; pwd`
TGT_PATH=`cd ${TGT_PATH} ; pwd`

echo "Source: ${SRC_PATH}"
echo "Target: ${TGT_PATH}"

for that in `find ${SRC_PATH} -type f` ; do
	path=`dirname $that`
	file=`basename $that`
	temp=`echo $path | grep .git`
	[ "$temp" != "" ] && continue
	temp=`find ${TGT_PATH} -name $file`
	for this in $temp ; do
		if [ -f "$this" ] ; then
			# in case the same file
			[ "$that" == "$this" ] && continue
			what=`basename $this`
			SUM1=`md5sum $that 2>/dev/null | cut -f1 -d' '`
			SUM2=`md5sum $this 2>/dev/null | cut -f1 -d' '`
			if [ "${file}" = "${what}" -a "${SUM1}" = "${SUM2}" ] ; then
				echo "[FOUND]"
				echo "  $file: $SUM1"
				echo "  $what: $SUM2"
				if [ "$CHK_EXEC" == "--exec" ] ; then
					echo -n "  Removing '$this'... "
					rm -rf $this
					echo "done."
				fi
			fi
		fi
	done
done
