#!/bin/bash

# chkgithub
# - written by azman@my1matrix.net
# - look up all repo on github belonging to a user account
# - clone if not already locally available

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
CURPATH="$(pwd)"

# look for config file
for conffile in "$CURPATH/.$MY1TOOL" "$HOME/.$MY1TOOL" ; do
	[[ ! -f $conffile ]] && continue
	source $conffile ; break
done

USERNAME=${USERNAME:=""}
ORGSNAME=${ORGSNAME:=""}
LISTNAME=${LISTNAME:="/tmp/list.txt"}
DO_CLONE=""
DO_LOCAL=""
DO_COUNT=""

while [ "$1" != "" ] ; do
	case $1 in
		--clone | --exec )
			DO_CLONE="YES"
			;;
		--local )
			shift
			[ ! -f "$1" ] &&
				echo "Local list file '$1' not found! Aborting..." && exit 1
			LISTNAME=$1
			DO_LOCAL="YES"
			;;
		--count )
			shift
			DO_COUNT="$1"
			;;
		--user )
			shift
			USERNAME="$1"
			;;
		--orgs )
			shift
			ORGSNAME="$1"
			;;
		* )
			echo "Unknown parameter ($1)!" && exit 1
			;;
	esac
	shift
done

if [ "$DO_LOCAL" != "YES" ] ; then
	[ "$USERNAME" == "" ] &&
		echo "Missing user info... abort!" && exit 1
	echo -n "" >$LISTNAME
	USRS_URL="https://api.github.com/users/$USERNAME/repos"
	ORGS_URL="https://api.github.com/orgs/$ORGSNAME/repos"
	if [ "$DO_COUNT" != "" ] ; then
		USRS_URL="${USRS_URL}?per_page=$DO_COUNT"
		ORGS_URL="${ORGS_URL}?per_page=$DO_COUNT"
	fi
	echo -n "Enter password for '$USERNAME': "
	CHK_LIST="$(curl -u $USERNAME $USRS_URL 2>/dev/null|grep full_name)"
	echo "$CHK_LIST"|sed 's/^.*: \"\(.*\)\".*$/\1/' >>$LISTNAME
	echo
	if [ "$ORGSNAME" != "" ] ; then
		echo -n "Enter password for '$USERNAME': "
		CHK_LIST="$(curl -u $USERNAME $ORGS_URL 2>/dev/null|grep full_name)"
		echo "$CHK_LIST"|sed 's/^.*: \"\(.*\)\".*$/\1/' >>$LISTNAME
		echo
	fi
	echo "Repository list saved in '$LISTNAME'."
else
	echo "Using repository list in '$LISTNAME'."
fi

for a in $(cat $LISTNAME); do
	b=${a#*/}
	echo -n "Checking '$b'... "
	[ -d "$b" ] && echo "found." && continue
	[ "$DO_CLONE" != "YES" ] && echo "no local copy." && continue
	echo "cloning this... "
	git clone git@github.com:${a}.git
done

exit 0
