#!/bin/bash

# chkgithub_gist
# - written by azman@my1matrix.org
# - look up all gists on github belonging to a user account
# - clone if not already locally available

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
CURPATH="$(pwd)"

# look for config file
for conffile in "$CURPATH/.$MY1TOOL" "$HOME/.$MY1TOOL" ; do
	[[ ! -f $conffile ]] && continue
	source $conffile ; break
done

USERNAME=${USERNAME:=""}
LISTNAME=${LISTNAME:="/tmp/list_gist.txt"}
DO_LOCAL=""
DO_COUNT="50"

while [ "$1" != "" ] ; do
	case $1 in
		--local )
			shift
			[ ! -f "$1" ] &&
				echo "Local list file '$1' not found! Aborting..." && exit 1
			LISTNAME=$1
			DO_LOCAL="YES"
			;;
		--list )
			shift
			LISTNAME=$1
			;;
		--count )
			shift
			DO_COUNT="$1"
			;;
		--user )
			shift
			USERNAME="$1"
			;;
		* )
			echo "Unknown parameter ($1)!" && exit 1
			;;
	esac
	shift
done

if [ "$DO_LOCAL" != "YES" ] ; then
	[ "$USERNAME" == "" ] &&
		echo "Missing user info... abort!" && exit 1
	echo -n "" >$LISTNAME
	USRS_URL="https://api.github.com/users/$USERNAME/gists"
	[ "$DO_COUNT" != "" ] && USRS_URL="${USRS_URL}?per_page=$DO_COUNT"
	CHK_GIST="git_pull_url|created_at|description"
	CHK_LIST="$(curl -i $USRS_URL 2>/dev/null|grep -E "$CHK_GIST")"
	echo "$CHK_LIST"|sed 's/^.*\": \"\(.*\)\".*$/\1/' >>$LISTNAME
	echo "Repository list saved in '$LISTNAME'."
else
	echo "Using repository list in '$LISTNAME'."
fi

GIST_LINK=""
GIST_PATH=""
while read -r line ; do
	if [ "$GIST_LINK" = "" ] ; then
		GIST_LINK=$line
		continue
	elif [ "$GIST_PATH" = "" ] ; then
		GIST_PATH=${line//:/_}
		continue
	fi
	GIST_NAME=${line}
	echo -n "Checking '$GIST_NAME'... "
	if [ -d "$GIST_PATH" ] ; then
		echo "local found."
	else
		git clone $GIST_LINK $GIST_PATH
	fi
	GIST_LINK=""
	GIST_PATH=""
done <$LISTNAME

exit 0
