#!/bin/bash

DATE_FMT="+%Y%m%d%H%M"
THISPATH=`pwd`
THISHOST=`hostname`
WORKPATH="/tmp"
WORKFILE="${THISHOST}_ip"
LOG_FILE=`basename $0 .sh`.log
TGT_HOST="$1"
DO_FORCE=${DO_FORCE:=""}

DATE=`date $DATE_FMT`
TOOL=`which ifconfig 2>/dev/null`
if [ ! -z "$TOOL" ] ; then
	CURR_IP=`ifconfig | grep -v 127.0.0.1 | grep 'inet '`
	CURR_IP=`echo $CURR_IP | sed 's/.*inet \([^\s]*\)\s.*/\1/'`
else
	TOOL=`which ip 2>/dev/null`
	if [ -z "$TOOL" ] ; then
		echo "** No tools to find IP address!"
		exit 1
	fi
	CURR_IP=`ip a | grep -v 127.0.0.1 | grep 'inet '`
	CURR_IP=`echo $CURR_IP | sed 's/.*inet \([^\/]*\)\/.*/\1/'`
fi
BASE_IP=`echo $CURR_IP | sed 's/\.[0-9]*$//'`

cd $WORKPATH
[ -f ${WORKFILE} ] && PREV_IP=`cut -f1 -d' ' ${WORKFILE}`
if [ "$CURR_IP" != "$PREV_IP" -o "$DO_FORCE" == "yes" ] ; then
	echo "$CURR_IP ($BASE_IP) [$DATE]" > ${WORKFILE}
	[ ! -f $LOG_FILE ] &&
		echo "[$DATE]: IP CHANGE LOG FILE CREATED" >> $LOG_FILE
	echo "[$DATE]: IP CHANGED {$PREV_IP} -> {$CURR_IP}" >> $LOG_FILE
	if [ "$TGT_HOST" != "" ]; then
		scp ${WORKFILE} ${TGT_HOST}
	else
		echo "[$DATE]: IP CHANGED {$PREV_IP} -> {$CURR_IP}"
	fi
else
	echo "[$DATE]: IP CHECK {$CURR_IP} ($BASE_IP)"
fi
cd $THISPATH
