#!/bin/bash

DATE_FMT="+%Y%m%d%H%M"
THISPATH=`pwd`
THISHOST=`hostname`
WORKPATH="/tmp"
WORKFILE="${THISHOST}_ip"
LOG_FILE=`basename $0 .sh`.log
TGT_HOST="$1"

CURR_IP=`ifconfig | grep -v 127.0.0.1 | grep 'inet '`
CURR_IP=`echo $CURR_IP | sed 's/.*inet \([^\s]*\)\s.*/\1/'`
BASE_IP=`echo $CURR_IP | sed 's/\.[0-9]*$//'`
#echo "CHECK_IP: $CURR_IP ($BASE_IP)"

cd $WORKPATH
[ -f ${WORKFILE} ] &&
	PREV_IP=`cut -f1 -d' ' ${WORKFILE}`
if [ "$CURR_IP" != "$PREV_IP" ] ; then
	echo "$CURR_IP ($BASE_IP) [$DATE]" > ${WORKFILE}
	DATE=`date $DATE_FMT`
	[ ! -f $LOG_FILE ] &&
		echo "[$DATE]: IP CHANGE LOG FILE CREATED" >> $LOG_FILE
	echo "[$DATE]: IP CHANGED {$PREV_IP} -> {$CURR_IP}" >> $LOG_FILE
	if [ "$TGT_HOST" != "" ]; then
		scp ${WORKFILE} ${TGT_HOST}
	else
		echo "[$DATE]: IP CHANGED {$PREV_IP} -> {$CURR_IP}"
	fi
fi
cd $THISPATH
