#!/bin/bash

# chknew
# - written by azman@my1matrix.org
# - check new configuration file
# - make the 'update' if requested

MY1TOOL=`basename $0`
MY1PATH=`dirname $0`
CURPATH=`pwd`
NEWPATH=${NEWPATH:="/etc"}

[ $UID -ne 0 ] && echo "Must run as root!" && exit 1

case "$1" in
	--switch | --list)
		CHKLIST=$1
		;;
	--help|-h)
		echo "Usage: $MY1TOOL [options]"
		echo "Options:"
		echo "  -h | --help   : Show this help"
		echo "       --list   : Just list all *.new files"
		echo "       --switch : Decide either to switch or remove"
		exit 0
		;;
	*)
		[ "$1" != "" ] && echo "Invalid param '$1'!" && exit 1
		;;
esac

NEWLIST=`find $NEWPATH -name "*.new"`
if [ "$NEWLIST" == "" ]; then
	echo "No NEW configuration files found!"
else
	for a in $NEWLIST; do
		b=${a//.new/}
		if [ ! -f "$b" ] ; then
			echo "File '$b' not found! Run with '--switch' to use '$a'."
			[ "$CHKLIST" == "--switch" ] && mv $a $b
			continue;
		fi
		c=`diff $b $a 2>&1`
		echo "==> File: $b"
		[ "$CHKLIST" == "--list" ] && continue
		if [ "$c" == "" ] ; then
			echo "  -- No changes?!"
			[ "$CHKLIST" == "--switch" ] &&
				rm -f $a && echo "File '$a' removed!" && echo
		else
			read -n 1 -p "Show? (y/n/q) " dummy ; echo
			[ "$dummy" == "y" ] && echo "$c"
			[ "$dummy" == "n" ] && continue
			[ "$dummy" == "q" ] && break
			if [ "$CHKLIST" == "--switch" ]; then
				read -n 1 -p "<S>witch <R>emove <*>Continue ? " dummy ; echo
				[ "$dummy" == "s" ] && mv $a $b && echo "File '$a' chosen!"
				[ "$dummy" == "r" ] && rm -f $a && echo "File '$a' removed!"
				echo
			fi
		fi
	done
fi

exit 0
