#!/bin/bash

# chkname
# - written by azman@my1matrix.net
# - check file/path name to remove whitespaces (option to convert lowercase)

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"

DO_HERE=""
DO_LOWER=""
DO_EXEC=""

[ "$(echo $@|grep -- '--here')" != "" ] && DO_HERE="YES"
[ "$(echo $@|grep -- '--lowercase')" != "" ] && DO_LOWER="YES"
[ "$(echo $@|grep -- '--exec')" != "" ] && DO_EXEC="YES"

function chk_file()
{
	# check files
	IFS_SAVE=$IFS
	IFS=$'\n'
	local files=($(find `pwd` -maxdepth 1 -type f | sort))
	IFS=$IFS_SAVE
	local tfile tconv loop
	for (( loop=0;loop<${#files[@]};loop++ )); do
		tfile="${files[$loop]}"
		tconv="$(echo "$tfile"|tr ' ' '_')"
		[ "$DO_LOWER" == "YES" ] && tconv="$(echo "$tconv"|tr '[A-Z]' '[a-z]')"
		if [ "$tconv" != "$tfile" ] ; then
			if [ "$DO_EXEC" == "YES" ]; then
				mv "$tfile" "$tconv"
			else
				echo "Candidate => '$tfile' to '$tconv'"
			fi
		fi
	done
}

function chk_path()
{
	if [ "$DO_HERE" == "" ] ; then
		# check paths
		IFS_SAVE=$IFS
		IFS=$'\n'
		local paths=($(find . -maxdepth 1 -type d))
		IFS=$IFS_SAVE
		local tcurr=`pwd`
		local tpath tconv loop
		for (( loop=0;loop<${#paths[@]};loop++ )); do
			tpath="${paths[$loop]}"
			[ "$tpath" = "." ] && continue
			tpath="${tcurr}${tpath:1}"
			tconv="$(echo "$tpath"|tr ' ' '_')"
			[ "$DO_LOWER" == "YES" ] &&
				tconv="$(echo "$tconv"|tr '[A-Z]' '[a-z]')"
			#echo "  [CHECK] '$tpath' => '$tconv'"
			if [ "$tconv" != "$tpath" ] ; then
				if [ "$DO_EXEC" == "YES" ]; then
					mv "$tpath" "$tconv"
					tpath="$tconv"
				else
					echo "Candidate => '$tpath' to '$tconv'"
				fi
			fi
			cd "$tpath"
			chk_path
			cd "$tcurr"
		done
	fi
	# process file in this path
	chk_file
}

chk_path

exit 0
