#!/bin/bash

# chkname
# - written by azman@my1matrix.org
# - check file/path name to remove whitespaces (option to convert lowercase)

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"

DO_HERE=""
DO_LOWER=""
DO_EXEC=""
DO_DOTS=""
DO_PAREN=""

[ "$(echo $@|grep -- '--here')" != "" ] && DO_HERE="YES"
[ "$(echo $@|grep -- '--lowercase')" != "" ] && DO_LOWER="YES"
[ "$(echo $@|grep -- '--exec')" != "" ] && DO_EXEC="YES"
[ "$(echo $@|grep -- '--dots')" != "" ] && DO_DOTS="YES"
[ "$(echo $@|grep -- '--brackets')" != "" ] && DO_PAREN="YES"

function chk_name()
{
	# check whitespace (default)
	local tconv="$(echo "$1"|tr ' ' '_')"
	# get part before extension
	local textd="${tconv##*.}"
	local ttemp="${tconv%.${textd}}"
	# remove dots except extension... IF requested
	[ "$DO_DOTS" == "YES" ] &&
		tconv="$(echo "$ttemp"|tr '.' '_').${textd}"
	# remove brackets... IF requested
	[ "$DO_PAREN" == "YES" ] &&
		tconv="$(echo "$tconv"|tr '(' '_'|tr ')' '_')"
	# change lowercase... IF requested
	[ "$DO_LOWER" == "YES" ] &&
		tconv="$(echo "$tconv"|tr '[A-Z]' '[a-z]')"
	# remove double underscore OR underscores beside hyphen
	tconv="$(echo "$tconv"|sed 's|__|_|g'|sed 's|_-_|-|g')"
	# remove underscore at end of name
	#tconv="$(echo "$tconv"|sed 's|^\(.*\)_$|\1|g')"
	# spit it out
	echo "$tconv"
}

function chk_file()
{
	local fpath=`pwd`
	# check files
	IFS_SAVE=$IFS
	IFS=$'\n'
	local files=($(find . -maxdepth 1 -type f | sed 's|\.\/||g' | sort))
	IFS=$IFS_SAVE
	local tfile tconv loop
	for (( loop=0;loop<${#files[@]};loop++ )); do
		tfile="${files[$loop]}"
		tconv=`chk_name "${tfile}"`
		if [ "$tconv" != "$tfile" ] ; then
			if [ "$DO_EXEC" == "YES" ]; then
				mv "$fpath/$tfile" "$fpath/$tconv"
			else
				echo "Candidate => '$tfile' to '$tconv'"
			fi
		fi
	done
}

function chk_path()
{
	if [ "$DO_HERE" == "" ] ; then
		# check paths
		IFS_SAVE=$IFS
		IFS=$'\n'
		local paths=($(find . -maxdepth 1 -type d))
		IFS=$IFS_SAVE
		local tcurr=`pwd`
		local tpath tconv loop
		for (( loop=0;loop<${#paths[@]};loop++ )); do
			tpath="${paths[$loop]}"
			[ "$tpath" = "." ] && continue
			tpath="${tpath:2}"
			tconv=`chk_name "${tpath}"`
			#echo "  [CHECK] '$tpath' => '$tconv'"
			if [ "$tconv" != "$tpath" ] ; then
				if [ "$DO_EXEC" == "YES" ]; then
					mv "$tcurr/$tpath" "$tcurr/$tconv"
					tpath="$tcurr/$tconv"
				else
					echo "Candidate => '$tpath' to '$tconv'"
				fi
			fi
			cd "$tpath"
			chk_path
			cd "$tcurr"
		done
	fi
	# process file in this path
	chk_file
}

chk_path

exit 0
