#!/bin/bash

# chknet
# - written by azman@my1matrix.net
# - simple script to check network from /sys/class/net/
# - also checks wireless info

INET_PATH="/sys/class/net"
INET_MISS="YES"

INET_DEVS=""
WIFI_DEVS=""
for dev in `find $INET_PATH -type l -maxdepth 1`; do
	[ "$dev" == "${INET_PATH}/lo" ] && continue;
	TEST=`cat ${dev}/carrier 2>/dev/null`
	[ "$TEST" != "1" ] && continue;
	TEST=`cat ${dev}/operstate 2>/dev/null`
	[ "$TEST" != "up" ] && continue;
	TEST=`basename ${dev}`
	if [ -d "${dev}/wireless" ] ; then
		WIFI_DEVS="${WIFI_DEVS}${TEST} "
	else
		INET_DEVS="${INET_DEVS}${TEST} "
	fi
done

INET_MAIN=`echo ${INET_DEVS} | cut -d' ' -f1`
WIFI_MAIN=`echo ${WIFI_DEVS} | cut -d' ' -f1`

function find_ip()
{
	local idev=$1
	# find ip address
	local curr=`ifconfig | grep "$idev" -A 2 | grep -v inet6 | grep inet`
	curr=`echo "$curr" | sed 's/^.*inet \([0-9.]*\).*$/\1/'`
	echo -n "$curr"
}

if [ "$INET_MAIN" != "" ] ; then
	CURR_IP=`find_ip "$INET_MAIN"`
	INET_MESG="ONLINE:{$INET_MAIN:$CURR_IP}"
elif [ "$WIFI_MAIN" != "" ] ; then
	CURR_IP=`find_ip "$WIFI_MAIN"`
	INET_MESG=`chkwifi $WIFI_MAIN --state | sed 's/{.*:\(.*\):\(.*\)}/\1:\2/'`
	INET_MESG="ONLINE:{$WIFI_MAIN:$CURR_IP:$INET_MESG}"
else
	INET_MESG="OFFLINE"
fi

[ "$1" == "--state" ] && echo "$INET_MESG" && exit 0

echo -n "Ethernet: $INET_MAIN ("`echo $INET_DEVS|wc -w`"), "
echo "WiFi: $WIFI_MAIN ("`echo $WIFI_DEVS|wc -w`")"

exit 0
