#!/bin/bash

# chkrc
# - written by azman@my1matrix.org
# - simple script to check executable rc scripts

THAT_PATH="/etc/rc.d"
SYST_EXEC="rc.4 rc.6 rc.K rc.M rc.S"

# find all executable rc scripts
LIST_EXEC=`find /etc/rc.d/ -perm /u+x -maxdepth 1 -mindepth 1 -type f`

for that in ${LIST_EXEC} ; do
	base=`basename $that`
	for temp in ${SYST_EXEC} ; do
		[ "$base" == "$temp" ] && base= && break
	done
	[ "$base" == "" ] && continue
	echo "Service: ${base#rc.}"
done

exit 0
