#!/bin/bash

# chksum
# - written by azman@my1matrix.net
# - create and check MD5 sum hashes

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
CURPATH="$(pwd)"
MD5FILE=${MD5FILE:="check.md5"}

# tool & env setup
MD5SUM_BIN=${MD5SUM_BIN:="$(which md5sum 2>/dev/null)"}
[[ "$MD5SUM_BIN" = "" ]] && echo "md5sum binary NOT found! Aborting!" && exit 1

if [ "$(echo $@|grep -- '--create')" != "" ]; then
	echo -n "" >$MD5FILE
	for a in $(find . -type f); do
		[[ "$(basename $a)" == "$MD5FILE" ]] && continue
		md5sum $a >>$MD5FILE
	done
else
	[[ ! -r "$MD5FILE" ]] && echo "Cannot find '$MD5FILE'!" && exit 1
	$MD5SUM_BIN --check $MD5FILE
fi

exit 0
