#!/bin/bash

# chkscreen
# - written by azman@my1matrix.org
# - simple display manager based on xrandr

# example using xrandr tool
# xrandr --output LVDS1 --auto --output VGA1 --mode 1024x768 --right-of LVDS1

FIX_THAT="NO"
FIX_NAME="DP-2"
FIX_MODE="1280x1024"
CHK_MODE="NO"
CHK_TASK=""
CHK_DISP=`xrandr -q | grep " connected" | sed 's/ .*$//g'`
CNT_DISP=`echo $CHK_DISP | wc -w`

fix_display()
{
	local base="/sys/class/drm"
	local name=$1
	local path="$base/card0-$name"
	local stat="$path/status"
	[ ! -r "$stat" ] && echo "Cannot read $stat!" && exit 1
	local what=`cat $stat | grep disconnected`
	if [ "$what" != "" ] ; then
		# only root can do this! :(
		echo "Must be root to write to $stat!"
		su - -c "echo 'on-digital' > $stat"
	fi
	exit 0
}

fix_resolution()
{
	local name=$1
	local mode=$2
	echo -n "Adding mode $mode for $name... "
	xrandr --addmode $name $mode
	echo "done!"
	exit 0
}

echo -n "We have $CNT_DISP connected display(s) ==>"
for DISP in $CHK_DISP ; do
	echo -n " [$DISP]"
done
echo "."
#DISP0=`echo "$CHK_DISP" | sed -n 1p`
#DISP1=`echo "$CHK_DISP" | sed -n 2p`
#DISP2=`echo "$CHK_DISP" | sed -n 3p`
#echo "-- Displays:{$DISP0,$DISP1,$DISP2}"

while [ "$1" != "" ]; do
	case $1 in
		--fix) FIX_THAT="YES" ;;
		--res) shift ; FIX_MODE=$1 ; CHK_MODE="YES" ;;
		--name) shift ; FIX_NAME=$1 ;;
		-*) echo "Unknown option '$1'!" ; exit 1 ;;
		*) CHK_TASK=$1 ;;
	esac
	shift
done

[ "$FIX_THAT" = "YES" ] && fix_display $FIX_NAME
[ "$CHK_MODE" = "YES" ] && fix_resolution $FIX_NAME $FIX_MODE
[ "$CHK_TASK" == "" ] && exit 0

if [ ${CNT_DISP} -gt 1 ] ; then
	if [ "$CHK_TASK" == "multi" -o "$CHK_TASK" == "dual" ] ; then
		echo -n "Applying multi-head configuration..."
		FULL0=
		for DISP in $CHK_DISP ; do
			if [ -z "$FULL0" ] ; then
				FULL0="--output $DISP --auto"
			else
				FULL0="$FULL0 --output $DISP --auto --right-of $DISP0"
			fi
			DISP0=$DISP
		done
		xrandr $FULL0
		echo "done."
	elif [ "$CHK_TASK" == "twin" ] ; then
		echo -n "Applying twin-view configuration..."
		FULL0=
		for DISP in $CHK_DISP ; do
			if [ -z "$FULL0" ] ; then
				FULL0="--output $DISP --auto"
			else
				FULL0="$FULL0 --output $DISP --auto --same-as $DISP0"
			fi
			DISP0=$DISP
		done
		xrandr $FULL0
		echo "done."
	elif [ "$CHK_TASK" == "single" ] ; then
		echo -n "Applying single-view configuration..."
		FULL0=
		for DISP in $CHK_DISP ; do
			if [ -z "$FULL0" ] ; then
				FULL0="--output $DISP --auto"
			else
				FULL0="$FULL0 --output $DISP --off"
			fi
			DISP0=$DISP
		done
		xrandr $FULL0
		echo "done."
	else
		echo "Command '$CHK_TASK' unknown!"
		exit 1
	fi
elif [ "$CHK_TASK" == "hres" ] ; then
	DISP=`echo "$CHK_DISP" | sed -n 1p`
	MODE="1280x1024@75"
	VCTO="138.75 1280 1368 1504 1728 1024 1027 1034 1072 -hsync +vsync"
	if [ "$(xrandr | grep "1280x1024@75   74.9*")" == "" ] ; then
		xrandr --newmode ${MODE} ${VCTO}
		xrandr --addmode ${DISP} ${MODE}
	fi
	if [ "$(xrandr | grep "connected ${MODE}")" == "" ] ; then
		xrandr --output ${DISP} --mode ${MODE}
	fi
else
	echo "Command '$CHK_TASK' unknown!"
	exit 1
fi

exit 0
