#!/bin/bash

# chktype
# - written by azman@my1matrix.net
# - create/compile a c program that prints primitive data type sizes
# - removes all created binary/source before exiting

CURR_PATH=`pwd`
TEMP_PATH="/tmp"
TEMP_CBIN="$(basename $0 .sh)"
TEMP_CSRC="${TEMP_CBIN}.c"

TYPE_CHECK=$(cat <<TYPECHECK
#include <stdio.h>
struct size_item_t {
	char name[12];
	size_t size;
};
struct size_item_t sizelist[] =
{
	{"char",sizeof(char)},
	{"int",sizeof(int)},
	{"short",sizeof(short)},
	{"long",sizeof(long)},
	{"long long",sizeof(long long)},
	{"float",sizeof(float)},
	{"double",sizeof(double)},
	{"long double",sizeof(long double)}
};
int sizesize = sizeof(sizelist)/sizeof(struct size_item_t);
int main(void)
{
	int loop;
	struct size_item_t* temp;
	printf("-----------------\\\\n");
	printf("C data type sizes\\\\n");
	printf("-----------------\\\\n");
	for (loop=0;loop<sizesize;loop++)
	{
		temp = &sizelist[loop];
		printf("Type:{%12s},Size:[%d]\\\\n",temp->name,temp->size);
	}
	return 0;
}
TYPECHECK
)

GCCCHECK=`which cc`
[ "$GCCCHECK" = "" ] && echo "Cannot find compiler 'cc'!" && exit 1

cd ${TEMP_PATH}
echo -e "$TYPE_CHECK" > ${TEMP_CSRC}
cc -o ${TEMP_CBIN} ${TEMP_CSRC}
[ $? -eq 0 ] && ./${TEMP_CBIN}
rm -rf ${TEMP_CBIN} ${TEMP_CSRC}
cd ${CURR_PATH}

exit 0
