#!/bin/sh

CHKEXEC=""
CHKFILE=""

name_outfile()
{
	local that="$1"
	[ ! -f "$that" ] && return
	local base=`basename $that`
	local tpnm=`basename $that .pnm`
	local tbmp=`basename $that .bmp`
	local tpng=`basename $that .png`
	if [ "$tpnm" != "$base" ] ; then
		echo -n "cat;$tpnm"
	elif [ "$tbmp" != "$base" ] ; then
		echo -n "bmptopnm;$tbmp"
	elif [ "$tpng" != "$base" ] ; then
		echo -n "pngtopnm;$tpng"
	fi
}

while [ "$1" != "" ]; do
	[ "$CHKFILE" != "" ] &&
		echo "Multiple input? ($CHKFILE)&($1)?!" && exit 1
	CHKTEMP=`name_outfile $1`
	[ "$CHKTEMP" = "" ] &&
		echo "Invalid input '$1'?!" && exit 1
	CHKFILE=$1
	CHKEXEC=`echo $CHKTEMP | cut -d';' -f1`
	OUTFILE=`echo $CHKTEMP | cut -d';' -f2`
	CHKPATH=`dirname $CHKFILE`
	[ "$CHKPATH" != "." ] &&
		CHKPATH=`cd $CHKPATH ; pwd` &&
		OUTFILE=${CHKPATH}/${OUTFILE}
	shift
done

[ "$CHKEXEC" == "" -o "$CHKFILE" == "" ] &&
	echo "No input given?" && exit 0

# a4 should be 210mm x 297mm @ 8.27in x 11.7in
TOPS_OPTS="-imageheight 11.7 -imagewidth 8.3"

${CHKEXEC} ${CHKFILE} | pnmtops ${TOPS_OPTS} | ps2pdf - ${OUTFILE}.pdf
