#!/bin/bash

# copy2bin
# - written by azman@my1matrix.org
# - simple script copy useful binary to my bin path

THAT_EXEC=
THAT_PATH=${THAT_PATH:="/home/share/slackware/slackbin"}

while [ ! -z "$1" ] ; do
	case $1 in
		--path) shift ; THAT_PATH=$1 ;;
		*)
			[ ! -x $1 ] && echo "Unknown param '$1'!" && exit 1
			THAT_EXEC=$1 ;;
	esac
	shift
done

[ "$THAT_EXEC" = "" ] && echo "No binary specified!" && exit 0

[ ! -x "$THAT_EXEC" ] && echo "Not an executable! {$THAT_EXEC}" && exit 1

[ ! -d "$THAT_PATH" ] && echo "Cannot find path! {$THAT_PATH}" && exit 1
THAT_PATH=`cd $THAT_PATH ; pwd`

echo -n "Copying binary '$THAT_EXEC' to '$THAT_PATH'... "
cp $THAT_EXEC ${THAT_PATH}/
echo "done."
