#!/bin/bash

QEMU_BIN=${QEMU_BIN:="qemu-system-i386"} # default is 32-bit!
QEMU_MEM=${QEMU_MEM:="1536M"} # 1.5G RAM!

CHK_THIS=`basename $0 | sed 's|do-||'`
CHK_PATH=`pwd`
CHK_CONF="$CHK_PATH/.$CHK_THIS"
[ -f "$CHK_CONF" ] && . $CHK_CONF

HDD_PATH=${HDD_PATH:="$CHK_PATH"}
HDD_FILE=${HDD_FILE:="$HDD_PATH/disk.qcow2"}
ISO_PATH=${ISO_PATH:="$CHK_PATH"}
ISO_LOAD=${ISO_LOAD:=""}

QEMU_OPT="${QEMU_OPT} -enable-kvm"
QEMU_OPT="${QEMU_OPT} -net nic -net user,hostfwd=tcp::2222-:22"
QEMU_OPT="${QEMU_OPT} -rtc base=localtime"

must_have_file()
{
	[ ! -f "$1" ] && echo "Missing file '$1'!" && exit 1
}

must_have_path()
{
	[ ! -d "$1" ] && echo "Missing path '$1'!" && exit 1
}

must_have_exec()
{
	[ -z "$1" ] && echo "Invalid '$1'!" && exit 1
	local exec=`which $1 2>/dev/null`
	[ $? -ne 0 ] && echo "Cannot exec '$1'!" && exit 1
}

while [ "$1" != "" ] ; do
	case $1 in
		--path2iso) shift ; must_have_path $1 ; ISO_PATH=`cd $1;pwd` ;;
		--path2hdd|--path) shift ; must_have_path $1 ; HDD_PATH=`cd $1;pwd` ;;
		--memory|-m) shift ; QEMU_MEM=$1 ;;
		--config) shift ; must_have_file $1 ; . $1 ;;
		--disk) shift ; HDD_FILE="$HDD_PATH/$1" ; must_have_file $HDD_FILE ;;
		--cdrom) shift ; ISO_LOAD="$ISO_PATH/$1" ; must_have_file $ISO_LOAD ;;
		--vga) QEMU_OPT="${QEMU_OPT} -vga cirrus" ;;
		--sound) QEMU_OPT="${QEMU_OPT} -soundhw ac97" ;;
		--amd64) QEMU_BIN="qemu-system-x86_64" ;;
		-* ) echo "Unknown option? ($1)" ; exit 1 ;;
		* ) echo "Unknown parameter? ($1)" ; exit 1 ;;
	esac
	shift
done

must_have_file $HDD_FILE
must_have_exec $QEMU_BIN

QEMU_OPT="${QEMU_OPT} -boot order=c -hda $HDD_FILE"
QEMU_OPT="${QEMU_OPT} -m ${QEMU_MEM}"
[ -f "$ISO_LOAD" ] && QEMU_OPT="${QEMU_OPT} -cdrom ${ISO_LOAD}"

$QEMU_BIN $QEMU_OPT
