#!/bin/bash

# droidbuild
# - written by azman@my1matrix.net
# - start shell for android sdk (with some utilities for android dev)

# using gradle - GRADLE_VERS is plugin version, NOT gradle version itself!
GRADLE_VERS=${GRADLE_VERS:="2.13"}
GRADLE_HOME=${GRADLE_HOME:="/home/share/tool/gradle"}
# set paths
SDK_PATH=${SDK_PATH:="/home/share/tool/android-sdk"}
TOOLPATH="${GRADLE_HOME}/bin:${SDK_PATH}/platform-tools:${SDK_PATH}/tools"
# set home
ANDROID_HOME=${ANDROID_HOME:="$SDK_PATH"}

export GRADLE_HOME PATH=$TOOLPATH:$PATH ANDROID_HOME

if [ "$1" == "" ] ; then
	# start a shell
	exec env PS1="(DROID-SDK) \u@\h:\w$ " KDE_SESSION_VERSION= $(which bash)
else
	COMMAND=$1
	shift
	case $COMMAND in
		create)
			PROJECT=${PROJECT:="$1"}
			[ "$PROJECT" == "" ] && PROJECT="my1defpro"
			TARGETP=${TARGETP:="android-23"}
			CHECKTGT="$(android list targets|grep $TARGETP)"
			[ "$CHECKTGT" == "" ] &&
				echo -e "Invalid target '$TARGETP'? Aborting!\n" && exit 1
			android create project --target ${TARGETP} --name ${PROJECT} \
				--path $(pwd)/${PROJECT} --activity MainActivity \
				--package org.my1matrix.${PROJECT} \
				--gradle --gradle-version ${GRADLE_VERS}
			;;
		*)
			echo "Unknown command(s) '$@'!"
			exit 1;
			;;
	esac
fi

exit 0
