#!/bin/bash

# droidbuild
# - written by azman@my1matrix.net
# - start shell for android sdk (with some utilities for android dev)

# using gradle - GRADLE_VERS is plugin version, NOT gradle version itself!
GRADLE_VERS=${GRADLE_VERS:="2.3.0"}
GRADLE_HOME=${GRADLE_HOME:="/home/share/tool/gradle"}
# android studio?
STUDIO_PATH=${STUDIO_PATH:="/home/share/appx/android-studio"}
# set paths
SDK_PATH=${SDK_PATH:="/home/share/tool/android-sdk"}
NDK_PATH=${NDK_PATH:="/home/share/tool/android-sdk/ndk-bundle"}
TOOLPATH=${TOOLPATH:=`pwd`}
[ -d "${STUDIO_PATH}/bin" ] &&
	TOOLPATH="${TOOLPATH}:${STUDIO_PATH}/bin"
# set gradle home
if [ -d "${GRADLE_HOME}/bin" ] ; then
	TOOLPATH="${TOOLPATH}:${GRADLE_HOME}/bin"
	export GRADLE_HOME
fi
# set sdk home path
if [ -d "$SDK_PATH" ] ; then
	TOOLPATH="${TOOLPATH}:${SDK_PATH}/platform-tools:${SDK_PATH}/tools"
	TOOLPATH="${TOOLPATH}:${SDK_PATH}/tools/bin"
	export ANDROID_HOME=${ANDROID_HOME:="$SDK_PATH"}
fi
# set ndk home path
if [ -d "$NDK_PATH" ] ; then
	TOOLPATH="${TOOLPATH}:${NDK_PATH}"
	export ANDROID_NDK_HOME=${ANDROID_NDK_HOME:="$NDK_PATH"}
fi
# export path
[ "$TOOLPATH" != "" ] && export PATH=$TOOLPATH:$PATH

# check java
TESTJAVA=`which java 2>/dev/null`
if [ "$TESTJAVA" == "" ] ; then
	# java not found, maybe in chroot?
	TESTJAVA=`file -L $(which sh) | grep 32-bit`
	[ "$TESTJAVA" != "" ] && export JAVA_HOME=
fi

if [ "$1" == "" ] ; then
	# start a shell
	exec env PS1="(DROID-SDK) \u@\h:\w$ " KDE_SESSION_VERSION= $(which bash)
else
	COMMAND=$1
	shift
	case $COMMAND in
		create)
			PROJECT=${PROJECT:="$1"}
			[ "$PROJECT" == "" ] && PROJECT="my1defpro"
			TARGETP=${TARGETP:="android-23"}
			CHECKTGT="$(android list targets|grep $TARGETP)"
			[ "$CHECKTGT" == "" ] &&
				echo -e "Invalid target '$TARGETP'? Aborting!\n" && exit 1
			android create project --target ${TARGETP} --name ${PROJECT} \
				--path $(pwd)/${PROJECT} --activity MainActivity \
				--package org.my1matrix.${PROJECT} \
				--gradle --gradle-version ${GRADLE_VERS}
			;;
		*)
			echo "Unknown command(s) '$@'!"
			exit 1;
			;;
	esac
fi

exit 0
