#!/bin/sh

FIND_TEXT=$1
FIND_PATH=`pwd`
TOOL_PATH=`dirname $0`

source_lib()
{
	local name=$1
	local full=$TOOL_PATH/$name
	[ ! -f "$full" ] && echo "Cannot find $full!" && exit 1
	. $full
}

source_lib libmy1slack
source_lib libmy1echo

for file in `find $FIND_PATH -not -path '*/\.*' -type f` ; do
	temp=`cat $file | grep $FIND_TEXT`
	[ "$temp" = "" ] && continue
	head_msg "\n==> $file\n"
	info_msg --no-tag "\n$temp\n"
done
echo
