#!/bin/sh

FILE_NAME=$1
DO_SECTOR=$2

[ ! -r "$FILE_NAME" ] && echo "Cannot read from '$FILE_NAME'!" && exit 1
[ -z "$DO_SECTOR" ] && DO_SECTOR=0

DO_SECTOR=$((DO_SECTOR*512))

hexdump -C -v -n 512 -s $DO_SECTOR $FILE_NAME | grep '|'
