#!/bin/bash

# getsync
# - written by azman@my1matrix.org
# - a getslack-like script to sync personal documents ('wrapper' for rsync)

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
CURPATH="$(pwd)"
CFGFILE="$CURPATH/.$MY1TOOL"

# look for config file
[ -f "$CFGFILE" ] && source $CFGFILE

# tool & env setup
SSH_PORT=${SSH_PORT:="22"}
SSH_EXEC=${SSH_EXEC:="ssh"}
[ "$SSH_PORT" -ne 22 ] && SSH_EXEC="ssh -p $SSH_PORT"
RSYNC=${RSYNC:="$(which rsync 2>/dev/null)"}
RSYNCOPT=${RSYNCOPT:="-rpltD --partial --progress --dry-run"}
# RSYNCURL="user@server:/path/to/home/"
RSYNCURL=${RSYNCURL:=""}
LOCALURL=${LOCALURL:="."}

# make sure rsync is available!
[ "$RSYNC" == "" ] && echo "Cannot find rsync!" && exit 1

# first parameter CAN be a path to server URL
[ -d "$1" ] && RSYNCURL="$(cd $1;pwd)/" && LOCALURL="." &&
	INCLUDES="$INCLUDES --include=/" && shift

# enforce this!
[ "$RSYNCURL" == "" ] && echo "Remote URL not specified!" && exit 1

# check target & source
RSYNCSRC="${RSYNCURL}"
RSYNCTGT="${LOCALURL}"

# customized sync list
EXCLUDES=${EXCLUDES:=""}
INCLUDES=${INCLUDES:=""}
[ -r "$EXCLUDEFILE" ] && EXCLUDES="--exclude-from=$EXCLUDEFILE"
[ -r "$INCLUDEFILE" ] && INCLUDES="--include-from=$INCLUDEFILE"

# check parameters
while  [ "$1" != "" ]; do
	case $1 in
		-h|--help)
			echo "Usage:"
			echo "  $(basename $0) [parameters] ..."
			echo "The script's parameters are:"
			echo "  --help            This help"
			echo "  --upload          Use local as source instead"
			echo "  --reload          Delete excluded files"
			echo "  --delete          Delete if not in source"
			echo "  --update          Sync newer files only"
			echo "  --no-delete       Cancels --delete"
			echo "  --no-update       Cancels --update"
			echo "  --dolink          Copy links as well (now default?)"
			echo "  --exec            Execute (else, only dry-run)"
			echo "  --timestamp       Update timestamps only (special case)"
			echo "  --exclude=/path/  Specify additional exclude path"
			echo "  --include=/path/  Specify additional include path"
			exit
			;;
		--upload)
			RSYNCTMP="${RSYNCSRC}"
			RSYNCSRC="${RSYNCTGT}"
			RSYNCTGT="${RSYNCTMP}"
			;;
		--reload)
			RSYNCOPT="${RSYNCOPT} --delete-excluded"
			;;
		--delete|--update)
			RSYNCOPT="${RSYNCOPT} $1"
			;;
		--no-delete)
			RSYNCOPT=`echo "${RSYNCOPT}"|sed 's/ --delete//'`
			;;
		--no-update)
			RSYNCOPT=`echo "${RSYNCOPT}"|sed 's/ --update//'`
			;;
		--dolink)
			RSYNCOPT="${RSYNCOPT} --copy-links --keep-dirlinks"
			;;
		--exec)
			RSYNCOPT=`echo "${RSYNCOPT}"|sed 's/ --dry-run//'`
			;;
		--timestamp)
			RSYNCOPT="${RSYNCOPT} --size-only"
			;;
		--exclude*)
			EXCLUDES="$EXCLUDES $1"
			;;
		--include*)
			INCLUDES="$INCLUDES $1"
			;;
		*)
			echo "Unknown parameter '$1'"
			exit 1
			;;
	esac
	shift
done
RSYNCOPT="${RSYNCOPT} ${INCLUDES} ${EXCLUDES}"

# start actual mirroring process
echo "*** From ${RSYNCSRC} To ${RSYNCTGT} ***"
$RSYNC -e "$SSH_EXEC" ${RSYNCOPT} ${RSYNCSRC} ${RSYNCTGT}
echo "$(date) [$$]: Done mirroring (exit code $?)."

exit 0
