#!/bin/bash

# getslack
# - written by azman@my1matrix.net
# - a 'reduced' version of alien_bob's mirror_slackware_current.sh

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
# look for config file
for conffile in "$(pwd)/.$MY1TOOL" "$HOME/.$MY1TOOL"; do
	[[ ! -f $conffile ]] && continue
	source $conffile ; break
done

# capture error in sub-shells
set -e # activates errexit

# tool & env setup
SLACKROOT=${SLACKROOT:="$(pwd)"}
[[ -z "$SLACKARCH" ]] && [[ -n "$ARCH" ]] && SLACKARCH=$ARCH
SLACKARCH=${SLACKARCH:="$(uname -m)"}
SLACKSUFX=${SLACKSUFX:=""}
[[ "$SLACKARCH" == "x86_64" ]] && SLACKSUFX="64"
SLACKFULL=${SLACKFULL:="slackware${SLACKSUFX}"}
[[ -z "$SLACKVERS" ]] && [[ -n "$RELEASE" ]] && SLACKVERS=$RELEASE
SLACKVERS=${SLACKVERS:="13.37"}
SLACKFULL="${SLACKFULL}-${SLACKVERS}"
SLACKPATH="${SLACKROOT}/${SLACKFULL}"
# setup rsync parameters
RSYNCURLROOT=${RSYNCURLROOT:="rsync.osuosl.org::slackware/"}
RSYNCURL=${RSYNCURL:="${RSYNCURLROOT}${SLACKFULL}"}
RSYNCOPT=${RSYNCOPT:="--delete --delete-excluded --partial -rlptD --progress"}
# check required binary
RSYNC=${RSYNC:="$(which rsync 2>/dev/null)"}
[[ "$RSYNC" == "" ]] && echo "Cannot find rsync! Aborting!" && exit 1

# customized default sync list
EXCLUDES=${EXCLUDES:="--exclude=pasture/ --exclude=testing/ --exclude=source/"}
INCLUDES=${INCLUDES:=""}
[[ -r "$EXCLUDEFILE" ]] && EXCLUDES="--exclude-from=$EXCLUDEFILE"
[[ -r "$INCLUDEFILE" ]] && INCLUDES="--include-from=$INCLUDEFILE"

# start actual mirroring process - reduced version of alien_bob's script
echo -e "#\n# Checking and changing to $SLACKPATH ...\n#"
[[ ! -d $SLACKPATH ]] && mkdir -pv $SLACKPATH
cd $SLACKPATH
umask 022

echo "*** Using ${RSYNCURL} ***"
$RSYNC ${RSYNCOPT} ${INCLUDES} ${EXCLUDES} ${RSYNCURL}/ .
echo "*** Using ${RSYNCURL} - (2nd Run) ***"
$RSYNC ${RSYNCOPT} ${INCLUDES} ${EXCLUDES} ${RSYNCURL}/ .
echo "$(date) [$$]: Done mirroring ${SLACKFULL} (exit code $?)."

exit 0
