#!/bin/bash

# getslack-multilib
# - written by azman@my1matrix.net
# - alien_bob's multilib package retriever

TOOL_NAME=`basename $0 .sh`
TOOL_PATH=`dirname $0`
# look for config file
for conf in `pwd`/.$TOOL_NAME $HOME/.$TOOL_NAME ; do
	[ -r $conf ] && source $conf && break
done
# setup path to slackware tree
[ -z "$SLACKROOT" ] && SLACKROOT=`pwd`
[ -z "$SLACKARCH" ] && [ -n "$ARCH" ] && SLACKARCH=$ARCH
[ -z "$SLACKARCH" ] && SLACKARCH=`uname -m`
[ "$SLACKARCH" == "x86_64" ] && SLACKSUFX="64" || SLACKSUFX=
[ -z "$SLACKNAME" ] && SLACKNAME="slackware$SLACKSUFX"
[ -z "$SLACKVERS" ] && [ -n "$VERS" ] && SLACKVERS=$VERS
[ -z "$SLACKVERS" ] && [ ! -f /etc/slackware-version ] && SLACKVERS="current" ||
	SLACKVERS=`cat /etc/slackware-version | sed 's/Slackware //'`
SLACKFULL=$SLACKNAME-$SLACKVERS
SLACKPATH=$SLACKROOT/$SLACKFULL-multilib
# capture error in sub-shells
set -e # activates errexit
# setup rsync stuffs (e.g. default rsync url)
[ -z "$RSYNCURLROOT" ] && RSYNCURLROOT="bear.alienbase.nl::mirrors/"
RSYNC_URL="${RSYNCURLROOT}people/alien/multilib/${SLACKVERS}/"
RSYNC_OPT="--delete --delete-excluded --partial -rlptD --progress"
# check if rsync binary is available
RSYNC_BIN=`which rsync 2>/dev/null`
[ "$RSYNC_BIN" == "" ] && echo "Cannot find rsync! Aborting!" && exit 1
# customized default sync list
[ -z "$EXCLUDES" ] && EXCLUDES="--exclude=debug/"
# start actual mirroring process - reduced version of alien_bob's script
echo -e "#\n# Checking and changing to $SLACKPATH ...\n#"
[ ! -d $SLACKPATH ] && mkdir -pv $SLACKPATH
cd $SLACKPATH
echo "*** Using $RSYNC_URL ***"
$RSYNC_BIN $RSYNC_OPT $INCLUDES $EXCLUDES $RSYNC_URL $SLACKPATH
echo `date`" [$$]: Done mirroring $SLACKFULL-multilib (exit code $?)."
exit 0
