#!/bin/bash

# icestorm
# - written by azman@my1matrix.net
# - start icestorm environment

MY1TOOL=`basename $0 .sh`
MY1PATH=`dirname $0`
# look for config file
for conffile in "$(pwd)/.$MY1TOOL" "$HOME/.$MY1TOOL"; do
	[ ! -f $conffile ] && continue
	source $conffile ; break
done

EXEPATH=${EXEPATH:="/home/share/tool/icestorm"}
export PATH=$EXEPATH/bin:$PATH

LIBPATH=$EXEPATH/lib
[ -d "$LIBPATH" ] && export LD_LIBRARY_PATH="$LIBPATH"

# start a shell
exec env PS1="(ICESTORM-EXEC) \u@\h:\w$ " `which bash 2>/dev/null`
exit 0
