#!/bin/sh

CHKEXEC=""
CHKFILE=""

while [ "$1" != "" ]; do
	case $1 in
		*)
			if [ "$CHKFILE" != "" ] ; then
				echo "Multiple input? ($CHKFILE)&($1)?!"
				exit 1
			else
				if [ -f $1 ] ; then
					CHKFILE="$1"
					CHKTEST=`basename $1`
					BMPFILE=`basename $1 .bmp`
					PNGFILE=`basename $1 .png`
					if [ "$BMPFILE" != "$CHKTEST" ] ; then
						CHKEXEC="bmptopnm"
						OUTFILE=$BMPFILE
					elif [ "$PNGFILE" != "$CHKTEST" ] ; then
						CHKEXEC="pngtopnm"
						OUTFILE=$PNGFILE
					else
						echo "Unknown file type '$1'?!"
						exit 1
					fi
					CHKPATH=`dirname $1`
					[ "$CHKPATH" != "." ] && OUTFILE=${CHKPATH}/${OUTFILE}
				else
					echo "Invalid file '$1'?! Aborting!"
					exit 1
				fi
			fi
			;;
	esac
	shift
done

[ "$CHKEXEC" == "" -o "$CHKFILE" == "" ] &&
	echo "No input given?" && exit 0

# a4 should be 210mm x 297mm @ 8.27in x 11.7in
TOPS_OPTS="-imageheight 11.7 -imagewidth 8.3"

${CHKEXEC} ${CHKFILE} | pnmtops ${TOPS_OPTS} | ps2pdf - ${OUTFILE}.pdf
