#!/bin/bash

# install_kernel
# - written by azman@my1matrix.org
# - simple script to install kernel from (built/made) linux kernel tree

CURR=`pwd`
FROM="/usr/src"
NAME="my1"
BOOT="vmlinuz"
CONF="config"
SMAP="System.map"
EXTD=`uname -m`
[ "$EXTD" = "x86_64" ] && EXTD=".x64" || EXTD=
EXEC=0
REDO=0

verify_path()
{
	[ ! -d $1 ] && echo "Invalid path '$1'!" && exit 1
}

while [ ! -z "$1" ] ; do
	case $1 in
		-x|--exec) EXEC=1 ;;
		-r|--redo) REDO=1 ;;
		-n|--name) NAME=$1 ;;
		-p|--path) verify_path $1 ; FROM=`cd $1 ; pwd` ;;
		-*) echo "Unknown option $1!" && exit 1 ;;
		[0-9]*) VERS=$1 ;;
		*) echo "Unknown param $1!" && exit 1 ;;
	esac
	shift
done

[ "$VERS" = "" ] && echo "No kernel version given!" && exit 1
FULL="linux-$VERS"
MAIN="$FROM/$FULL"
[ ! -d "$MAIN" ] && echo "Cannot find kernel path '$MAIN'!" && exit 1
cd $MAIN
MODS="/lib/modules/$VERS"

BOOT_SRC="arch/x86/boot/bzImage"
CONF_SRC=".$CONF"
SMAP_SRC="$SMAP"
BOOT_TGT="$BOOT-$NAME-$VERS"
CONF_TGT="$CONF-$NAME-$VERS$EXTD"
SMAP_TGT="$SMAP-$NAME-$VERS"
BOOT_CHK="/boot/$BOOT_TGT"
CONF_CHK="/boot/$CONF_TGT"
SMAP_CHK="/boot/$SMAP_TGT"

echo "Path:{$MAIN} Version:{$VERS}"

if [ $UID -ne 0 ] ; then
	echo "Must be root!"
	echo "-- $BOOT_SRC => $BOOT_CHK"
	echo "-- $CONF_SRC => $CONF_CHK"
	echo "-- $SMAP_SRC => $SMAP_CHK"
	exit 1
fi

redo_target()
{
	local file=$1
	if [ -f "$file" ] ; then
		echo -n "Removing target '$file'... "
		rm $file
		[ $? -eq 0 ] && echo "done." || echo "error?"
	fi
}

if [ $REDO -ne 0 ] ; then
	redo_target $BOOT_CHK
	redo_target $CONF_CHK
	redo_target $SMAP_CHK
fi

check_source()
{
	local file=$1
	[ ! -f "$file" ] && echo "Cannot find '$file'! Aborting!" && exit 1
}
check_source $BOOT_SRC
check_source $CONF_SRC
check_source $SMAP_SRC

check_target()
{
	local file=$1
	[ -f "$file" ] && echo "Target exists '$file'! Aborting!" && exit 1
}
check_target $BOOT_CHK
check_target $CONF_CHK
check_target $SMAP_CHK

if [ $EXEC -ne 0 ] ; then
	echo -n "Install kernel... "
	cp $BOOT_SRC $BOOT_CHK
	cp $CONF_SRC $CONF_CHK
	cp $SMAP_SRC $SMAP_CHK
	echo "done."
	if [ -d "$MODS" ] ; then
		echo "Modules path '$MODS' detected!"
	else
		echo -h "Install modules... "
		make modules_install
		echo "done."
	fi
fi
