#!/bin/bash

# iso2boot
# - written by azman@my1matrix.org
# - modified from slack2iso

ISOPATH=${ISOPATH:="$HOME/temp"}
ISOFILE=${ISOFILE:="bootable.iso"}
DIRPATH=${DIRPATH:=`pwd`}
APP_ID_=${APP_ID_:="APP ID"}
VOL_ID_=${VOL_ID_:="VOL ID"}

while [ "$1" != "" ] ; do
	case $1 in
		--file )
			shift
			ISOFILE="$1"
			;;
		--path )
			shift
			ISOPATH="$1"
			;;
		--from )
			shift
			[ ! -f "$1" ] && echo "Not a valid source path ($1)!" && exit 1
			DIRPATH=`cd $1;pwd`
			;;
		--app_id )
			shift
			APP_ID_="$1"
			;;
		--vol_id )
			shift
			VOL_ID_="$1"
			;;
		* )
			echo "Unknown parameter ($1)!" && exit 1
			;;
	esac
	shift
done

MKISOFS=$(which mkisofs 2>/dev/null)
[ "$MKISOFS" == "" ] && echo "Cannot find mkisofs! Aborting!" && exit 1

[ ! -d "$ISOPATH" ] &&
	echo "Creating target ISO path '$ISOPATH'... " && mkdir -p $ISOPATH

ISOFULL=${ISOPATH}/${ISOFILE}
LOGFILE=${ISOFILE%.*}_build.log
[ -f "$ISOFULL" ] &&
	echo "Removing ISO '$ISOFILE' in '$ISOPATH'... " && rm -f $ISOFULL

cd $DIRPATH
echo -n "Creating ISO in '$ISOPATH' from '$DIRPATH'... "
$MKISOFS -o $ISOFULL \
	-V "${VOL_ID_}" -A "${APP_ID_} (build $(date +%Y%m%d))" \
	-R -J -hide-rr-moved -hide-joliet-trans-tbl -d -N -v \
	-sort isolinux/iso.sort \
	-b isolinux/isolinux.bin -c isolinux/isolinux.boot \
	-no-emul-boot -boot-load-size 4 -boot-info-table \
	-eltorito-alt-boot -e images/efiboot.img \
	. >${LOGFILE} 2>&1
echo "done!"
cd - >/dev/null

ISOHYBRID=$(which isohybrid 2>/dev/null)
if [ -x "$ISOHYBRID" ] ; then
	cd $ISOPATH
	echo -n "Making $ISOFILE in '$ISOPATH' an isohybrid... "
	$ISOHYBRID $ISOFILE >>${LOGFILE} 2>&1
	if [ $? -ne 0 ] ; then echo "error??" ; else echo "done!" ; fi
	cd - >/dev/null
fi

exit 0
