#!/bin/bash

# libmy1get
# - written by azman@my1matrix.org
# - library functions for downloading stuff

do_download()
{
	local fname="$1" # source full name
	local label="$2" # label local copy (if different name)
	local cpath=`pwd`
	local cname=""
	[ "$fname" == "" ] && exit 1 # shouldn't be here?
	[ "$label" == "" ] && label="$fname"
	[ "${fname//$label/}" == "${fname}" ] && cname="--output-document=$label"
	echo -ne "\nDownloading $label:     "
	wget $cname --no-use-server-timestamps --progress=dot "$fname" 2>&1 | \
		grep --line-buffered "%" | sed -u -e "s,\.,,g" | \
		awk '{printf("\b\b\b\b%4s", $2)}'
	[ ! -r "$label" ] &&
		echo -e "\nCannot download source $fname to $cpath/$label!\n" && exit 1
	echo -e "\b\b\b\b DONE!\n"
}

do_loadball()
{
	local pkg_path=$1 # path to store the loaded ball
	local pkg_file=$2 # source full name (url!)
	local pkg_ball=`basename $pkg_file`
	local cur_path=`pwd`
	[ ! -d $pkg_path ] &&
		echo -e "[ERROR] Cannot find $pkg_path!\n" >&2 && exit 1
	# TODO! This has problems if redirected a lot (github source?)
	#wget --spider $pkg_file >/dev/null 2>&1
	#[ $? -ne 0 ] && echo -e "[ERROR] Cannot get $pkg_file!\n" >&2 && exit 1
	local chk_test=`curl -s -o /dev/null -w '%{http_code}' $pkg_file`
	[ $chk_test -ne 200 -a $chk_test -ne 301 \
			-a $chk_test -ne 302 -a $chk_test -ne 303 \
			-a $chk_test -ne 226 ] &&
		echo -e "[ERROR] Cannot get $pkg_file! ($chk_test)\n" >&2 && exit 1
	cd $pkg_path
	do_download $pkg_file $pkg_ball 2>/dev/null
	[ ! -r $pkg_ball ] &&
		echo -e "[ERROR] Cannot download $pkg_ball!\n" >&2 && exit 1
	cd $cur_path
	return 0
}
