#!/bin/bash

# libmy1echo
# - written by azman@my1matrix.org
# - library functions for fancy echoing... ooo! colors!

MY1ECHO_DEBUG=${MY1ECHO_DEBUG:="NO"}

tag_msg()
{
	local mtag=""
	local ctag="39" # default color
	local elog="" # log filename
	local eout="yes" # warnings/errors should go to stderr!
	local dbug="no"
	while [ "$1" != "" ]; do
		case $1 in
			--log) shift ; elog="$1" ;;
			--tag) shift ; mtag="$1" ;;
			--color) shift ; ctag="$1" ;;
			--debug) dbug="yes" ;;
			--no-tag) mtag="" ;;
			--stdout) eout="no" ;;
			--stderr) eout="yes" ;;
			*) break ;;
		esac
		shift
	done
	[ "$elog" != "" ] && echo -ne "$mtag $@" >>$elog
	[ "$dbug" = "yes" -a "$MY1ECHO_DEBUG" = "NO" ] && return 0
	if [ "$eout" = "yes" ] ; then
		[ "$mtag" != "" ] && echo -ne "\033[1;${ctag}m${mtag}\033[0m " >&2
		echo -ne "\033[1;${ctag}m$1\033[0m" >&2
	else
		[ "$mtag" != "" ] && echo -ne "\033[1;${ctag}m${mtag}\033[0m "
		echo -ne "\033[1;${ctag}m$1\033[0m"
	fi
	return 0
}

error_msg()
{
	local color_tag="31" # red
	tag_msg --tag "[ERROR]" --color "$color_tag" "$@"
}

error_exit()
{
	echo ; error_msg "$@"
	exit 1
}

debug_msg()
{
	local color_tag="36" # cyan
	tag_msg --tag "[DEBUG]" --color "$color_tag" --debug "$@"
}

debug_chk()
{
	[ "$1" = "no" ] && MY1ECHO_DEBUG="NO" || MY1ECHO_DEBUG="YES"
}

check_msg()
{
	local color_tag="34" #blue
	tag_msg --tag "[CHECK]" --color "$color_tag" --stdout "$@"
}

warn_msg()
{
	local color_tag="33" # yellow
	tag_msg --tag "[WARN]" --color "$color_tag" "$@"
}

head_msg()
{
	local color_tag="34" #blue
	tag_msg --color "$color_tag" --stdout "$@"
}

info_msg()
{
	local color_tag="32" # green
	tag_msg --tag "[INFO]" --color "$color_tag" --stdout "$@"
}

format_text()
{
	# format is "\033[<attr>;<textcolor>;<backcolor>m" \033 = \e (ESC char)
	local ends="\033[0m"
	# attributes
	local bold="1" # bright (bold on xterm?)
	local dim="2" # dim
	local uline="4"
	local blink="5" # doesn't work on xterm (only real console!)
	local reverse="7"
	local hidden="8"
	# text colors
	local black="30" # for background Xm + 10m
	local red="31"
	local green="32"
	local yellow="33"
	local blue="34"
	local magenta="35"
	local cyan="36"
	local white="37"
	local default="39"
	# check options
	local attr color text
	while [ "$1" != "" ] ; do
		case "$1" in
		--reset) attr="0" ;;
		--bold) attr=$bold ;;
		--blink) attr=$blink ;;
		--color)
			shift; color="$1"
			case "$color" in
				black) color="$black" ;;
				red) color="$red" ;;
				green) color="$green" ;;
				yellow) color="$yellow" ;;
				blue) color="$blue" ;;
				magenta) color="$magenta" ;;
				cyan) color="$cyan" ;;
				white) color="$white" ;;
				*) color="$default" ;;
			esac
			;;
		*)
			[ "$MY1_DEBUG" == "YES" ] &&
				echo "Attribute: $attr, Color: $color"
			if [ "$color" != "" ] ; then
				[ "$attr" == "" ] && attr="0"
				color="\033[${attr};${color}m"
			else
				[ "$attr" != "" ] &&
					color="\033[${attr}m"
			fi
			if [ "$color" == "" ] ;  then
				text="${text}${1} "
			else
				text="${text}${color}${1}${ends} "
			fi
			attr="" color=""
			;;
		esac
		shift
	done
	echo -e "$text"
}
