#!/bin/bash

# libtoolvideo
# - written by azman@my1matrix.org
# - library functions for video-tool
#   = basically a wrapper script for various tools

video_must_have_input()
{
	local ivid=$1
	[ -z "$ivid" ] && exit 0
	[ ! -f "$ivid" ] &&
		echo -ne "\n[ABORT] Input file missing ($ivid)!\n\n" && exit 0
}

video_prepare_output()
{
	local ivid=$1
	local ovid=$2
	[ -z "$ovid" ] && ovid="${ivid%.*}_conv.avi"
	echo -n $ovid
}

video_prepare_audio()
{
	local ivid=$1
	local aout=$2
	[ -z "$aout" ] && aout="${ivid%.*}_conv.mp3"
	echo -n $aout
}

video_check_output()
{
	local ovid=$1
	[ -f "$ovid" ] &&
		echo -ne "\n[ABORT] Output file exists ($ovid)!\n\n" && exit 0
}

video_convert()
{
	local ivid=$1 ; shift
	# default settings
	local vres=${vres:="704:304"}
	local vasp=${vasp:="16:9"}
	local vbit=${vbit:="700k"}
	local vqsc=${vqsc:="6"}
	local aqsc=${aqsc:="4"}
	# check params
	local ovid pas2 dvar dlog=/dev/null
	local vchk vlen
	while [ "$1" != "" ]; do
		case $1 in
			--var) dvar="yes" ;;
			--log) dlog="$ovid.log" ;;
			--2pass) pas2="yes" ;;
			--vbit) shift ; vbit=$1 ;;
			--vqsc) shift ; vqsc=$1 ;;
			--aqsc) shift ; aqsc=$1 ;;
			--output) shift ; ovid=$1 ;;
			--tv) vres="512:384" ; vasp="4:3" ;; #mod16 resolution
			--vlen) shift ; vlen=$1 ;;
			--init) shift ; vchk=$1 ;;
			*) echo -ne "\n[ABORT] Unknown param '$1'!\n\n" && exit 0
		esac
		shift
	done
	video_must_have_input $ivid
	ovid=`video_prepare_output $ivid $ovid`
	video_check_output $ovid
	local acod="-ar 48000 -ab 128k"
	local vcod="-vf scale=$vres -aspect $vasp -vb $vbit -r 25"
	[ "$dvar" = "yes" ] && pas2="" && acod="-qscale:a $aqsc" &&
		vcod="-qscale:v $vqsc -vf scale=$vres -aspect $vasp -r 25"
	# -qscale:v 4 is for mpegX stuffs!
	# -crf 18 is for libx264!
	# tinker with numbers
	#ffplay -vf eq=gamma=1.5:saturation=1.3 $ivid
	#ffplay -vf eq=brightness=0.06:saturation=2 $ivid
	# render
	#ffmpeg -i $ivid -vf eq=gamma=1.5:saturation=1.3 -c:a copy $ovid
	#ffmpeg -i $ivid -vf eq=brightness=0.06:saturation=2 -c:a copy $ovid
	# global options
	local gopt="-sn" # disable subtitle
	# audio options
	local aopt="-c:a libmp3lame $acod"
	# video options
	local vopt="-c:v mpeg4 -vtag xvid $vcod"
	local iopt
	[ ! -z "$vchk" ] && iopt="$iopt -ss $vchk"
	[ ! -z "$vlen" ] && gopt="$gopt -t $vlen"
	# convert!
	echo "Input : $ivid"
	echo "Output: $ovid"
	echo "Settings: {A:$acod,V:$vcod,init:$vchk,vlen:$vlen}"
	echo -n "" >${dlog}
	if [ "$pas2" != "yes" ]; then
		echo -n "Processing... "
		ffmpeg ${iopt} -i ${ivid} ${gopt} ${aopt} ${vopt} ${ovid} 2>>${dlog}
		echo "done."
	else
		local chk1="${iopt} -y"
		local chk2="${iopt} "
		local opt1="-pass 1 ${gopt} ${aopt} ${vopt} -an -f avi /dev/null"
		local opt2="-pass 2 ${gopt} ${aopt} ${vopt} ${ovid}"
		echo -n "Processing (PASS1)... "
		ffmpeg ${chk1} -i ${ivid} ${opt1} 2>>${dlog}
		echo -ne "done.\nProcessing (PASS2)... "
		ffmpeg ${chk2} -i ${ivid} ${opt2} 2>>${dlog}
		echo "done."
	fi
}

video_split_audio()
{
	local ivid=$1
	local aout=$2
	video_must_have_input $ivid
	aout=`video_prepare_audio $ivid $aout`
	video_check_output $aout
	# audio options
	local aopt="-c:a libmp3lame -ar 48000 -ab 128k"
	echo "Input: $ivid"
	echo -n "Extracting audio to '$aout'..."
	ffmpeg -i $ivid -vn $aopt $aout >/dev/null 2>&1
	[ $? -eq 0 ] && echo "done." || echo "error?"
}

video_split_video()
{
	local ivid=$1
	local vout=$2
	video_must_have_input $ivid
	vout=`video_prepare_output $ivid $ovid`
	video_check_output $vout
	echo "Input: $ivid"
	echo -n "Extracting video to '$vout'..."
	ffmpeg -i $ivid -vcodec copy -an -y $vout >/dev/null 2>&1
	[ $? -eq 0 ] && echo "done." || echo "error?"
}

video_merge_audio()
{
	local vchk=$1
	local achk=$2
	local ovid=$3
	video_must_have_input $vchk
	video_must_have_input $achk
	[ -z "$ovid" ] &&
		echo -ne "\n[ABORT] Output file not given!\n\n" && exit 0
	video_check_output $ovid
	echo "Inputs: {$vchk,$achk}"
	echo -n "Merging video/audio into '$ovid'..."
	ffmpeg -i $vchk -i $achk -vcodec copy -acodec copy -y $ovid >/dev/null 2>&1
	[ $? -eq 0 ] && echo "done." || echo "error?"
}

video_cut()
{
	local ivid=$1 ; shift
	# default video length is 1 minute
	local vchk vlen="1:00"
	while [ "$1" != "" ]; do
		case $1 in
			--vlen) shift ; vlen=$1 ;;
			--init) shift ; vchk=$1 ;;
			*) echo -ne "\n[ABORT] Unknown param '$1'!\n\n" && exit 0
		esac
		shift
	done
	[ ! -z "$vchk" ] && vchk="-ss $vchk"
	vlen="-t $vlen"
	video_must_have_input $ivid
	ovid=`video_prepare_output $ivid $ovid`
	video_check_output $ovid
	echo "Input: $ivid"
	echo -n "Cutting (init:$vchk,time:$vlen) into $ovid... "
	ffmpeg $vchk -i $ivid $vlen -c copy $ovid >/dev/null 2>&1
	[ $? -eq 0 ] && echo "done." || echo "error?"
}

video_mp4join()
{
	# list is a text file containing list of mp4 files to be joined
	# - 1 file per line
	# - format: "file <filename>"
	local list=$1
	local ovid=$2
	video_must_have_input $list
	ovid=`video_prepare_output $list $ovid`
	video_check_output $ovid
	echo "List: $list"
	echo -n "Joining video into '$ovid'... "
	ffmpeg -f concat -i $list -c copy $ovid
	[ $? -eq 0 ] && echo "done." || echo "error?"
}
