#!/bin/bash

# make_link
# - written by azman@my1matrix.org
# - simple script to copy all item in path as link

THAT_PATH=$1
[ ! -d "$THAT_PATH" ] && echo "Invalid path '$THAT_PATH'!" && exit 1
THAT_PATH=`cd $THAT_PATH;pwd`
HERE_PATH=$2
[ ! -z "$HERE_PATH" -a ! -d "$HERE_PATH" ] &&
	echo "Invalid path '$HERE_PATH'!" && exit 1

make_link()
{
	local that=$1
	local here=$2
	local curr=`pwd`
	[ -d "$here" ] && cd $here
	here=`pwd`
	echo "Creating links in '$here':"
	local path name
	for path in `find $that -mindepth 1 -maxdepth 1` ; do
		[ "$path" = "$that" ] && continue
		name=`basename $path`
		echo -n "-- $name -> ($path) ... "
		ln -sf $path .
		[ $? -eq 0 ] && echo "done." || echo "error?"
	done
	cd $curr
}

make_link $THAT_PATH $HERE_PATH

exit 0
