#!/bin/bash

# make_kernel
# - written by azman@my1matrix.org
# - make new kernel for slackware
# - should extract kernel source in /usr/src
#   = matters when creating link to source when installing!

PICK_CURR=`pwd`
PICK_BASE=`basename $PICK_CURR`
PICK_NAME=`echo $PICK_BASE | cut -d'-' -f1`
[ "$PICK_NAME" != "linux" ] && echo "Not a linux tree? ($PICK_CURR)" && exit 1
PICK_VERS=`echo $PICK_BASE | cut -d'-' -f2`
PICK_INIT=0
PICK_EXEC=0
PICK_CONF=0

while [ ! -z "$1" ] ; do
	case $1 in
		-i|--init) PICK_INIT=1 ;;
		-x|--exec) PICK_EXEC=1 ;;
		-c|--conf) PICK_CONF=1 ;;
		-*) echo "Unknown option $1!" && exit 1 ;;
		*) echo "Unknown param $1!" && exit 1
	esac
	shift
done

echo "Making kernel '$PICK_VERS' in '$PICK_CURR'"

if [ $PICK_INIT -ne 0 ] ; then
	# config copy
	COPY_EXTD=`uname -m`
	[ "$COPY_EXTD" = "x86_64" ] && COPY_EXTD=".x64" || COPY_EXTD=
	COPY_VERS=`uname -r`
	COPY_CONF="/boot/config-generic-${COPY_VERS}$COPY_EXTD"
	[ ! -f "$COPY_CONF" ] && echo "Cannot find $COPY_CONF!" && exit 1
	cp $COPY_CONF .config
	echo "-- Running make olddefconfig..."
	make olddefconfig
fi

# if required, run another make config to customize
[ $PICK_CONF -ne 0 ] && make menuconfig

# build kernel AND modules
if [ $PICK_EXEC -ne 0 ] ; then
	echo "-- Making kernel..."
	make bzImage modules
	[ $? -ne 0 ] && echo "Something went wrong???" && exit 1
	echo "-- Kernel $PICK_BASE ready!"
fi

exit 0
