#!/bin/bash

# maxisbb
# - written by azman@my1matrix.net
# - to get connected to 3G broadband network using HUAWEI device

HUAWEI_DEV_FILE="/dev/ttyUSB0"
PPPD_LOG_FILE="/tmp/$(basename $0)-pppd.log"

if [ "$1" == "down" ] ; then
	ETH_DEV="$2"
	ETH_DEV=${ETH_DEV:="eth0"}
	echo "Stopping server at ethernet device '$ETH_DEV'"
	DHCPD_PID="$(cat /var/run/dhcpd.pid 2>/dev/null)"
	ps $DHCPD_PID >/dev/null
	if [ $? -ne 0 ] || [ $DHCPD_PID == "" ] ; then
		echo "dhcpd not running"
	else
		kill -s SIGKILL $DHCPD_PID
	fi
	bash /etc/rc.d/rc.firewall stop
	bash /etc/rc.d/rc.ip_forward stop
	exit 0
fi

if [ "$1" == "server" ] ; then
	ETH_DEV="$2"
	ETH_DEV=${ETH_DEV:="eth0"}
	echo "Running server at ethernet device '$ETH_DEV'"
	/sbin/ifconfig $ETH_DEV up
	/usr/sbin/dhcpd $ETH_DEV
	bash /etc/rc.d/rc.ip_forward start
	bash /etc/rc.d/rc.firewall start
	exit 0
fi

if [ "$1" == "stop" ] ; then
	PPP_DEV=$(find /var/run -name ppp*.pid)
	PPP_DEV=${PPP_DEV%.pid}
	PPP_DEV=${PPP_DEV#/var/run/}
	if [ "$PPP_DEV" == "" ] ; then
		echo "No pppd running!"
	else
		PPP_PID=$(cat /var/run/${PPP_DEV}.pid)
		ps $PPP_PID >/dev/null
		if [ $? -ne 0 ] || [ $PPP_PID == "" ] ; then
			echo "pppd not running?!"
		else
			echo -n "Terminating pppd (${PPP_DEV}.pid)... "
			kill -s SIGKILL $PPP_PID
			echo "done [$?]."
		fi
	fi
	exit 0
fi

echo -n "Checking if device is plugged in... "
if [ ! -r $HUAWEI_DEV_FILE ] ; then
	echo "Not found!"
	exit 1
fi
echo "done."

# check if pppd already running?
PPP_DEV=$(find /var/run -name ppp*.pid)
PPP_DEV=${PPP_DEV%.pid}
PPP_DEV=${PPP_DEV#/var/run/}
if [ "$PPP_DEV" != "" ] ; then
	PPP_PID=$(cat /var/run/${PPP_DEV}.pid)
	ps $PPP_PID >/dev/null
	if [ $? -eq 0 ] && [ $PPP_PID != "" ] ; then
		echo "pppd already running (PID=$PPP_PID)"
		exit 0
	fi
fi

ETH_DEV=$(/sbin/ifconfig | grep eth)
ETH_DEV=${ETH_DEV%% *}
if [ ! "$ETH_DEV" == "" ] ; then
	echo "Taking down $ETH_DEV device!"
	/sbin/ifconfig $ETH_DEV down
fi

MY1_DEV_E220=$(cat <<MY1DEV1
/dev/ttyUSB0 460800
connect '/usr/sbin/chat -v -f /etc/ppp/chat-maxisbb'
defaultroute lock
debug ipcp-accept-remote ipcp-accept-local
persist usepeerdns noipdefault
name maxis
remotename MAXISBB
password wap
MY1DEV1
)
#echo "$MY1_DEV_E220" >/etc/ppp/huawei-e220

MY1_CHATSEQ=$(cat <<MY1CHAT
ABORT 'BUSY'
ABORT 'NO CARRIER'
'' ATZ
OK AT+CGDCONT=1,"IP","maxisbb"
OK ATDT*99#
CONNECT ''
MY1CHAT
)
#echo "$MY1_CHATSEQ" >/etc/ppp/chat-maxisbb

echo -n "" >$PPPD_LOG_FILE
echo -n "Connecting to Huawei-e220 device ..."
pppd call huawei-e220 logfile $PPPD_LOG_FILE 1>>$PPPD_LOG_FILE 2>>$PPPD_LOG_FILE
if [ $? -ne 0 ] ; then
	echo "Error detected!"
	exit 1
fi

# sleep a bit so pppd can finish its job
while [ "$(/sbin/ifconfig | grep ppp)" == "" ] ; do
	echo -n "."
	CHECK_MSGS="$(cat $PPPD_LOG_FILE)"
	if [ "$(echo "$CHECK_MSGS" | grep "Connect script failed")" != "" ] ; then
		echo "Connect script failed!"
		exit 1
#	elif [ "$(echo "$CHECK_MSGS" | grep "is locked by pid")" != "" ] ; then
#		PROC_PID=$(echo "$CHECK_MSGS" | grep "is locked by pid")
#		PROC_PID=${PROC_PID##*is locked by pid }
#		echo "Device locked by process PID=$PROC_PID!"
	fi
	sleep 1
done
echo " done!"

# update resolv.conf with file created by pppd
echo "# File created by $(basename $0) from pppd [$(date)]" >/etc/resolv.conf
cat /etc/ppp/resolv.conf >>/etc/resolv.conf

PPP_DEV=$(/sbin/ifconfig | grep ppp)
PPP_DEV=${PPP_DEV%% *}
echo "PPP device: '$PPP_DEV'"

exit 0
