#!/bin/bash

# nodejs-exec
# - written by azman@my1matrix.net
# - prepare shell to run nodejs stuff

export NODE_PATH=${NODE_PATH:="/home/share/tool/node-js"}
export NWJS_PATH=${NWJS_PATH:="/home/share/tool/nwjs-sdk"}

# start a shell
[ -d "$NODE_PATH" ] &&
	export PATH=${NODE_PATH}/bin:$PATH
[ -d "$NWJS_PATH" ] &&
	export PATH=${NWJS_PATH}:$PATH
exec env PS1="(NODEJS-EXEC) \u@\h:\w$ " `which bash 2>/dev/null`
exit 0
