#!/bin/bash

# packthis
# - written by azman@my1matrix.net
# - to pack current working directory into a tar.bz2 archive

CURRPATH=$(pwd)
WORKPATH=$(dirname $CURRPATH)
BALLPATH=$HOME/temp
BALLNAME=$(basename $CURRPATH)
BALLSUFX=${BALLSUFX:=""}
DATE_FMT=${DATE_FMT:="+%Y%m%d"}
CHECKGIT=${CHECKGIT:="YES"}
CHK_VERB=${CHK_VERB:="NO"}
TAR_OPTS=${TAR_OPTS:="cjf"}
CHK_COPY=${CHK_COPY:=""}
NUM_COPY=${NUM_COPY:=0}

while [[ "$1" != "" ]]; do
	case $1 in
		--suffix)
			shift
			BALLSUFX="-$1"
			;;
		--time)
			DATE_FMT="+%Y%m%d%H%M"
			;;
		--ignore-git)
			CHECKGIT="NO"
			;;
		--verbose|-v)
			CHK_VERB="YES"
			;;
		* )
			echo "Unknown parameter ($1)!" && exit 1
			;;
	esac
	shift
done

[[ "$CHK_VERB" == "YES" ]] && TAR_OPTS="${TAR_OPTS}v"

[[ "$CHECKGIT" == "YES" ]] && [[ -d "$CURRPATH/.git" ]] && BALLSUFX="${BALLSUFX}_git"

[[ ! -d $BALLPATH ]] && mkdir -pv $BALLPATH

if [[ -d $WORKPATH ]]; then
	cd $WORKPATH
	[[ "$CHK_VERB" == "NO" ]] && echo -n "Archiving ... "
	while [[ -f ${BALLPATH}/${BALLNAME}${BALLSUFX}-$(date ${DATE_FMT})${CHK_COPY}.tar.bz2 ]]; do	
		(( NUM_COPY=NUM_COPY+1 ))
		CHK_COPY="_${NUM_COPY}"
	done
	tar $TAR_OPTS ${BALLPATH}/${BALLNAME}${BALLSUFX}-$(date ${DATE_FMT})${CHK_COPY}.tar.bz2 ${BALLNAME}
	[[ "$CHK_VERB" == "NO" ]] && echo "done."
fi
