#!/bin/bash

# part_label
# - used to write partition name for my luks partition
# - somehow, it got the name from previously written devuan installer image

DISK_NAME=$1
[ ! -r "$DISK_NAME" ] && echo "Cannot read $DISK_NAME!" && exit 1
NEW_LABEL=$2

# 32768 + 40 + 4096 = 32808 + 4096 = 36904
# @ 32k + 4k + 40 = 36k + 40 (why 36k? GPT?)
# LBA 72 (512-sector 72) => offset 40
# 0x9028 - 00 44 -> 00 'M'
DISK_OFFS=36904
NAME_SIZE=16
FULL_SIZE=32

echo "-------------"
echo "Current Name:"
echo "-------------"
hexdump -C -v -n $FULL_SIZE -s $DISK_OFFS $DISK_NAME | grep '|'
[ -z "$NEW_LABEL" ] && exit 0

NEXT_SIZE=${#NEW_LABEL}
[ ${NEXT_SIZE} -lt 1 -o ${NEXT_SIZE} -gt ${NAME_SIZE} ] &&
	echo "Invalid partition label '$NEW_LABEL'!" && exit 1

# create temp file
TEMP_BUFF="ptname.tmp"
[ -f "$TEMP_BUFF" ] && echo "Temp file $TEMP_BUFF exists!" && exit 1
CONV_OPTS="conv=notrunc"
DD_OPTS=" bs=1 count=1 $CONV_OPTS"
dd if=/dev/zero of=$TEMP_BUFF bs=1 count=$FULL_SIZE >/dev/null 2>&1
for loop in `eval echo "{0..$((NAME_SIZE-1))}"` ; do
	skip=$((loop*2+1))
	temp=" "
	[ $loop -lt $NEXT_SIZE ] && temp="${NEW_LABEL:$loop:1}"
	#echo "Writing '$temp' to $TEMP_BUFF (seek=$skip)"
	echo -n "$temp" | dd of=$TEMP_BUFF seek=$skip $DD_OPTS >/dev/null 2>&1
done
echo "---------"
echo "New Name:"
echo "---------"
hexdump -C -v $TEMP_BUFF

# do the change!
DD_OPTS=" bs=1 count=$FULL_SIZE $CONV_OPTS"
dd if=$TEMP_BUFF of=$DISK_NAME seek=$DISK_OFFS $DD_OPTS >/dev/null 2>&1
echo "-------------"
echo "Changed Name:"
echo "-------------"
hexdump -C -v -n $FULL_SIZE -s $DISK_OFFS $DISK_NAME | grep '|'

rm -rf $TEMP_BUFF
exit 0
