#!/bin/bash

# robo-exec
# - written by azman@my1matrix.net
# - prepare shell to run stage multi-robot simulator

export STAGE_PATH=${STAGE_PATH:="/home/share/tool/stage"}
ARCH_BITS=""
if [ "$(uname -m)" == "x86_64" ] ; then
	ARCH_BITS="64"
	# stage lib is without 64 when using my1ubuild?
	[ ! -d ${STAGE_PATH}/lib${ARCH_BITS} ] && ARCH_BITS=""
fi
export STAGEPATH=${STAGE_PATH}/lib${ARCH_BITS}:.
export LD_LIBRARY_PATH=${STAGEPATH}
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${STAGEPATH}/pkgconfig
# start a shell
export PATH=$STAGE_PATH/bin:$PATH
exec env PS1="(ROBO-EXEC) \u@\h:\w$ " `which bash 2>/dev/null` --norc
exit 0
