#!/bin/bash

# robo-exec
# - written by azman@my1matrix.net
# - prepare shell to run player/stage

export PLAY_PATH=${PLAY_PATH:="/home/share/application/player"}
export STAGE_PATH=${STAGE_PATH:="/home/share/application/stage"}
ARCH_BITS=""
[[ "$(uname -m)" == "x86_64" ]] && ARCH_BITS="64"

export PLAYERPATH=${PLAY_PATH}/lib${ARCH_BITS}
export STAGEPATH=${STAGE_PATH}/lib${ARCH_BITS}
export LD_LIBRARY_PATH=${PLAYERPATH}:${STAGEPATH}
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${PLAYERPATH}/pkgconfig:${STAGEPATH}/pkgconfig
# start a shell
THISPATH="$PLAY_PATH/bin:$STAGE_PATH/bin"
export PATH=$THISPATH:$PATH
exec env PS1="(ROBO-EXEC) \u@\h:\w$ " $(which bash)

exit 0
