#!/bin/bash

# slacklive
# - written by azman@my1matrix.net
# - slackware live builder (incomplete...)

# standard tool info
MY1_TOOLNAME="my1 Slackware Live Builder"
MY1_TOOLVERS="2012.03.00"
MY1_TOOLBASE=$(basename $0 .sh)
MY1_TOOLPATH=$(cd $(dirname $0);pwd)
MY1_TOOL_LIB="libmy1slack"
# look for config file
for config in $(pwd) $MY1_TOOLPATH $HOME; do
	config=$config/.$MY1_TOOLBASE
	[[ ! -f $config ]] && continue
	source $config ; break
done
# look for my1slack library
[[ -r "$MY1_TOOLPATH/$MY1_TOOL_LIB" ]] &&
	source $MY1_TOOLPATH/$MY1_TOOL_LIB

function process_command()
{
	local command=$1 ; shift
	case $command in
		build)
			echo "Will be implemented later..."
			echo
			exit 0
			;;
		-h|--help|help)
			echo "Usage: $TOOL_THISFILE [command] [parameter]"
			echo "Available commands:"
			echo "  build  : Build"
			echo "         > -c | --select   : Insert (default)"
			echo "         > -u | --unselect : Delete instead"
			echo "         > -f | --file     : Specify filename"
			echo "         > -s | --sort     : Sort package list"
			echo "  help   : Show this help message"
			echo
			;;
		*)
			echo -e "Unknown command!\n"
			exit 1
			;;
	esac
}

# BEGIN MAIN SCRIPT

echo -e "\n$TOOL_THISFILE - $MY1_TOOLNAME ($MY1_TOOLVERS)\n"
process_command $TOOL_COMMANDS

# END MAIN SCRIPT
