#!/bin/bash

# slack2iso
# - written by azman@my1matrix.org
# - a section from alien_bob's mirror_slackware_current.sh

# standard tool info
TOOL_NAME=`basename $0`
TOOL_PATH=`dirname $0`
TOOL_PATH=`cd $TOOL_PATH ; pwd`

source_lib()
{
	local name=$1
	local full=$TOOL_PATH/$name
	[ ! -f "$full" ] && echo "Cannot find $full!" && exit 1
	. $full
}

source_lib libmy1slack
call_setup

[ ! -d $SLACKTREE ] && echo "Cannot find Slackware in $SLACKTREE" && exit 1
[ -d "$1" ] && ISOPATH=`cd $1 ; pwd`
ISOPATH=${ISOPATH:="$HOME/temp"}
ISONAME=${ISONAME:="${SLACKFULL}-install.iso"}
ISOFILE=$ISOPATH/$ISONAME

# make sure we have the tool
MKISOFS=`which mkisofs 2>/dev/null`
[ "$MKISOFS" == "" ] && echo "Cannot find mkisofs! Aborting!" && exit 1

# check target path
[ ! -d "$ISOPATH" ] &&
	echo "Creating target ISO path '$ISOPATH'... " && mkdir -p $ISOPATH
[ -f "$ISOFILE" ] &&
	echo "Removing ISO '$ISOFILE'... " && rm -rf $ISOFILE

cd $SLACKTREE
echo -n "Creating ISO in '$ISOPATH' from '$SLACKTREE'... "
$MKISOFS -o $ISOFILE \
	-V "${SLACKFULL} Install DVD" \
	-A "${SLACKFULL} Install DVD (build $(date +%Y%m%d))" \
	-R -J -hide-rr-moved -hide-joliet-trans-tbl -d -N -v \
	-sort isolinux/iso.sort \
	-b isolinux/isolinux.bin -c isolinux/isolinux.boot \
	-no-emul-boot -boot-load-size 4 -boot-info-table \
	. >$ISOPATH/${SLACKFULL}-install_build.log 2>&1
echo "done!"
cd - >/dev/null

ISOHYBRID=`which isohybrid 2>/dev/null`
if [ -x "$ISOHYBRID" ] ; then
	cd $ISOPATH
	echo -n "Making $ISONAME in '$ISOPATH' an isohybrid... "
	$ISOHYBRID $ISONAME >>$ISOPATH/${SLACKFULL}-install_build.log 2>&1
	[ $? -ne 0 ] && echo "error??" || echo "done!"
	cd - >/dev/null
fi

exit 0
