#!/bin/bash

# slacktest
# - written by azman@my1matrix.net
# - my1slack test script (mainly to test libmy1slack functions)

# standard tool info
MY1_TOOLNAME="my1 Slackware Test Script"
MY1_TOOLVERS="2012.03.00"
MY1_TOOLBASE=$(basename $0 .sh)
MY1_TOOLPATH=$(cd $(dirname $0);pwd)
MY1_TOOL_LIB="libmy1slack"
# look for config file
for config in $(pwd) $HOME; do
	config=$config/.$MY1_TOOLBASE
	[[ -r $config ]] && source $config && break
done
# look for my1slack library
[[ -r "$MY1_TOOLPATH/$MY1_TOOL_LIB" ]] && source $MY1_TOOLPATH/$MY1_TOOL_LIB

# BEGIN MAIN SCRIPT

echo -e "\n$MY1_TOOLBASE - $MY1_TOOLNAME ($MY1_TOOLVERS)\n"
if [[ "$@" != "" ]]; then
	echo -e "[SLACKTEST] Executing '$@'...\n"
	test_value="\"$1\" "
	shift
	for word in "$@"; do
		test_value="$test_value \"$word\""
	done
	eval "$test_value"
	echo -e "\n[SLACKTEST] Done.\n"
fi

# END MAIN SCRIPT
