#!/bin/bash

# slack2iso
# - written by azman@my1matrix.net
# - a section from alien_bob's mirror_slackware_current.sh

SLACKROOT=${SLACKROOT:="$(pwd)"}
[[ -z "$SLACKARCH" ]] && [[ -n "$ARCH" ]] && SLACKARCH=$ARCH
SLACKARCH=${SLACKARCH:="$(uname -m)"}
SLACKSUFX=${SLACKSUFX:=""}
[[ "$SLACKARCH" == "x86_64" ]] && SLACKSUFX="64"
SLACKFULL=${SLACKFULL:="slackware${SLACKSUFX}"}
[[ -z "$SLACKVERS" ]] && [[ -n "$RELEASE" ]] && SLACKVERS=$RELEASE
SLACKVERS=${SLACKVERS:="13.37"}
SLACKFULL="${SLACKFULL}-${SLACKVERS}"
SLACKPATH="${SLACKROOT}/${SLACKFULL}"
[[ ! -d "$SLACKPATH" ]] &&
	echo "Path to Slackware '$SLACKPATH' not found!" && exit 1

[[ -d "$1" ]] && ISOPATH="$(cd $1;pwd)"
ISOPATH=${ISOPATH:="$HOME/temp"}
ISOFILE=${ISOFILE:="${SLACKFULL}-install.iso"}

MKISOFS=$(which mkisofs 2>/dev/null)
[[ "$MKISOFS" == "" ]] && echo "Cannot find mkisofs! Aborting!" && exit 1
[[ ! -d "$ISOPATH" ]] &&
	echo "Creating target ISO path '$ISOPATH'... " && mkdir -p $ISOPATH

cd $SLACKPATH
[[ ! -f "$ISOFILE" ]] &&
	echo "Removing ISO '$ISOFILE' in '$ISOPATH'... " && rm -f $ISOFILE
echo -n "Creating ISO in '$ISOPATH' from '$SLACKPATH'... "
$MKISOFS -o $ISOPATH/$ISOFILE \
	-V "${SLACKFULL} Install DVD" \
	-A "${SLACKFULL} Install DVD (build $(date +%Y%m%d))" \
	-R -J -hide-rr-moved -hide-joliet-trans-tbl -d -N -v \
	-sort isolinux/iso.sort \
	-b isolinux/isolinux.bin -c isolinux/isolinux.boot \
	-no-emul-boot -boot-load-size 4 -boot-info-table \
	. >$ISOPATH/${SLACKFULL}-install_build.log 2>&1
echo "done!"
cd - >/dev/null

ISOHYBRID=$(which isohybrid 2>/dev/null)
if [[ -x "$ISOHYBRID" ]] ; then
	cd $ISOPATH
	echo -n "Making $ISOFILE in '$ISOPATH' an isohybrid... "
	$ISOHYBRID $ISOFILE >>$ISOPATH/${SLACKFULL}-install_build.log 2>&1
	if [[ $? -ne 0 ]] ; then echo "error??" ; else echo "done!" ; fi
	cd - >/dev/null
fi

exit 0
