#!/bin/bash

# slack-update
# - written by azman@my1matrix.net
# - get updates for slackware system
# - requires getslack, getslackpack, getslackbuild scripts

# standard tool info
TOOL_NAME=`basename $0`
TOOL_PATH=`dirname $0`
TOOL_PATH=`cd $TOOL_PATH ; pwd`
CURR_PATH=`pwd`
TOOL_DESC="my1 Slackware Update Tool"
TOOL_VERS="2019.07.00"

echo -ne "\n$TOOL_NAME - $TOOL_DESC ($TOOL_VERS)\n\n"

# find libmy1slack
[ ! -f $TOOL_PATH/libmy1slack ] &&
	echo "Cannot find libmy1slack!" && exit 1
. $TOOL_PATH/libmy1slack

# make sure we are in correct path
call_setup
[ ! -d "$SLACKTREE" ] &&
	echo "Cannot find slack @'$SLACKTREE'!" && exit 1
cd `dirname $SLACKTREE` ; echo "Log file $LOGS_FULL"

$TOOL_PATH/getslack
$TOOL_PATH/getslackpack --sweep --exec
$TOOL_PATH/getslackbuild -a

if [ -d /opt/chroot32 ] ; then
	ARCH=x86 $TOOL_PATH/getslack
	ARCH=x86 $TOOL_PATH/getslackpack --sweep --exec
fi

cd $CURR_PATH
echo ; exit 0
