#!/bin/bash

# slacktest
# - written by azman@my1matrix.net
# - my1slack test script

# standard tool info
TOOL_THISFUNC="my1 Slackware Test Script"
TOOL_THISVERS="2010.06.00"
# standard tool conf
TOOL_CHECKCMD="$@"
TOOL_COMMANDS=${TOOL_CHECKCMD:="--help"}
TOOL_THISFILE=$(basename $0 .sh)
TOOL_LOCATION=$(cd $(dirname $0);pwd)
TOOL_CONFFILE="$TOOL_THISFILE.conf"
TOOL_MY1SLACK="libmy1slack"
# look for config file
for conf_path in  $(pwd) $TOOL_LOCATION ; do
	config_file="${conf_path}/${TOOL_CONFFILE}"
	[[ -r $config_file ]] && source $config_file && break
done
# look for my1slack library
[[ -r "$TOOL_LOCATION/$TOOL_MY1SLACK" ]] && source $TOOL_LOCATION/$TOOL_MY1SLACK

# BEGIN MAIN SCRIPT

echo -e "\n$TOOL_THISFILE - $TOOL_THISFUNC ($TOOL_THISVERS)\n"
if [[ "$@" != "" ]]; then
	echo -e "[SLACKTEST] Executing '$@'...\n"
	$@
	echo -e "\n\n[SLACKTEST] Done.\n"
fi

# END MAIN SCRIPT
