#!/bin/bash

SSR_SCR=${SSR_SCR:="3"}
SSR_COL=${SSR_COL:="400"} # width
SSR_ROW=${SSR_ROW:="300"} # height
SSR_CAM="mplayer"

CAM_DEV=`find /dev -name "video*"`
[ "$CAM_DEV" = "" ] && echo "Cannot find camera? Abort!" && exit 1

CAM_OPT="tv:// -tv driver=v4l2:width=$SSR_COL:height=$SSR_ROW"
CAM_OPT="$CAM_OPT -vo xv -geometry 0%:0% -noborder -ontop -screen $SSR_SCR"

$SSR_CAM $CAM_OPT 2>/dev/null
