#!/bin/bash

CHK_NAME=""
CHK_LINE="\n"
DATE_FMT=${DATE_FMT:="+%Y%m%d"}
CHK_EXEC="NO"

while [ "$1" != "" ]; do
	case $1 in
		--exec) CHK_EXEC="YES" ;;
		--time) DATE_FMT="+%Y%m%d%H%M" ;;
		--seconds) DATE_FMT="+%Y%m%d%H%M%S" ;;
		--string) CHK_LINE="" ;;
		*)
			if [ "$CHK_NAME" != "" ] ; then
				echo "** Unknown parameter ($1)!" >&2
				exit 1
			elif [ ! -w "$1" ] ; then
				echo "** Cannot write/modify '$1'!" >&2
				exit 1
			fi
			CHK_NAME="$1"
			;;
	esac
	shift
done

if [ -w "$CHK_NAME" ] ; then
	CHK_BASE=${CHK_NAME%.*}
	if [ "$CHK_BASE" != "$CHK_NAME" ] ; then
		CHK_EXTN=${CHK_NAME##*.}
		NEW_NAME="${CHK_BASE}_"`date ${DATE_FMT}`".${CHK_EXTN}"
	else
		NEW_NAME="${CHK_NAME}_"`date ${DATE_FMT}`
	fi
	echo -n "-- Stamping $CHK_NAME => $NEW_NAME "
	if [ "$CHK_EXEC" != "YES" ] ; then
		echo "(DRY-RUN)"
	else
		mv $CHK_NAME $NEW_NAME
		echo "... done."
	fi
else
	echo -ne `date ${DATE_FMT}`"$CHK_LINE"
fi
