#!/bin/sh

# vga-suspend
# - got this from a discussion forum (Slax/Slackware)

# find video card's ID
ID=$(/sbin/lspci | grep VGA | awk '{ print $1 }' | sed -e 's@0000:@@' -e 's@:@/@')

# create a temporary file
TMP_FILE=$(mktemp /tmp/video_state.XXXXXX)

# setup escape route
trap 'rm -f $TMP_FILE' 0 1 15

# switch to vterm 1 to avoid graphics corruption in X
chvt 1

# save to hw clock?
/sbin/hwclock --systohc

# write all unwritten data (just in case)
sync

# dump video card data to temporary file
cat /proc/bus/pci/$ID > $TMP_FILE

# suspend-to-ram
echo -n mem > /sys/power/state
# OR, suspend-to-disk
# echo -n disk > /sys/power/state

# update system clock upon recovering
/sbin/hwclock --hctosys

# restore video card data from the temporary file
cat $TMP_FILE > /proc/bus/pci/$ID

# switch back to vterm 7 (running X)
chvt 7

# remove temporary file
rm -f $TMP_FILE
