#!/bin/bash

# video conversion examples
#
# quick one
# > video-tool convert <file> --var
# slightly larger, better quality
# > video-tool convert <file> --var6
# smaller size
# > video-tool convert <file> --2pass --vbit 450k
# small mp4 (360p)
# > video-tool convert-mp4 <file>

TOOL_NAME=`basename $0`
TOOL_PATH=`dirname $0`
TOOL_PATH=`cd $TOOL_PATH;pwd`

source_lib()
{
	local name=$1
	local full=$TOOL_PATH/$name
	[ ! -f "$full" ] && echo "Cannot find $full!" && exit 1
	. $full
}
source_lib libtoolvideo

TOOL_TASK="$1" ; shift
case "$TOOL_TASK" in
	help) video_help $@ ;;
	convert) video_convert $@ ;;
	convert-mp4) video_convert_mp4 $@ ;;
	split-video) video_split_video $@ ;;
	split-audio) video_split_audio $@ ;;
	merge-audio) video_merge_audio $@ ;;
	cut) video_cut $@ ;;
	join-mp4) video_mp4join $@ ;;
	play) video_play $@ ;;
	*) [ "$TOOL_TASK" != "" ] && echo "Unknown task '$TOOL_TASK'!" ;;
esac

exit 0
