#!/bin/bash

# xil-exec
# - written by azman@my1matrix.net
# - start xilinx apps or xilinx-env shell

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
# look for config file
for conffile in "$(pwd)/.$MY1TOOL" "$HOME/.$MY1TOOL"; do
	[[ ! -f $conffile ]] && continue
	source $conffile ; break
done

XILINX_VERS=${XILINX_VERS:="12.1"}
XILINX_PATH=${XILINX_PATH:="/home/share/application/xilinx-${XILINX_VERS}"}
ARCH_BITS="32"
BIN_TYPE=$(file -L /bin/bash)
if [[ "$(echo $BIN_TYPE | grep 'ELF 32-bit LSB executable')" == "" ]] ; then
	ARCH_BITS="64"
fi
XILINX_ARCH=${XILINX_ARCH:="$ARCH_BITS"}
XILINX_CONF=${XILINX_CONF:="${XILINX_PATH}/ISE/settings${XILINX_ARCH}.sh"}
XILEDK_CONF=${XILEDK_CONF:="${XILINX_PATH}/EDK/settings${XILINX_ARCH}.sh"}
PATH_ARCH=""
[[ "$XILINX_ARCH" == "64" ]] && PATH_ARCH=$XILINX_ARCH

if [ -r $XILINX_CONF ] ; then
	source $XILINX_CONF
else
	echo "Cannot find $XILINX_CONF!"
	exit 1
fi

if [ -r $XILEDK_CONF ] ; then
	source $XILEDK_CONF
else
	echo "Cannot find $XILEDK_CONF!"
	exit 1
fi

# allow ISE/EDK to use the USB Cable Driver
#export XIL_IMPACT_USE_LIBUSB=1
# added to override usage of system's tcl library
# may not need this on slack13.0 (tcl8.5.7)
#export LD_PRELOAD=${XILINX}/lib/${PLATFORM}/libtcl8.4.so
# added to use a working cable driver
#export LD_PRELOAD="$LD_PRELOAD /home/ftp/software/usb-driver/libusb-driver.so"

if [ "$1" == "" ] ; then
	# start a shell
	THISPATH="$XILINX_PATH/EDK/gnu/microblaze/lin${PATH_ARCH}/bin:$XILINX_PATH/EDK/gnu/powerpc-eabi/lin${PATH_ARCH}/bin"
	export PATH=$THISPATH:$PATH
	exec env PS1="(XIL-EXEC) \u@\h:\w$ " KDE_SESSION_VERSION= $(which bash)
else
	target=$1
	shift
	[ "$target" == "edk" ] && xps $1
	[ "$target" == "ise" ] && ise $1
	[ "$target" == "imp" ] && impact $1
fi

exit 0

