#!/bin/bash

# xil-exec
# - written by azman@my1matrix.net
# - start xilinx apps or xilinx-env shell

MY1TOOL="$(basename $0 .sh)"
MY1PATH="$(dirname $0)"
# look for config file
for conffile in "$(pwd)/.$MY1TOOL" "$HOME/.$MY1TOOL"; do
	[ ! -f $conffile ] && continue
	source $conffile ; break
done

XILINX_VERS=${XILINX_VERS:="12.1"}
XILINX_PATH=${XILINX_PATH:="/home/share/apps/xilinx-${XILINX_VERS}"}
ARCH_BITS="32"
BIN_TYPE=$(file -L /bin/bash)
if [ "$(echo $BIN_TYPE | grep 'ELF 32-bit LSB executable')" == "" ] ; then
	ARCH_BITS="64"
fi
XILINX_ARCH=${XILINX_ARCH:="$ARCH_BITS"}
XILINX_CONF=${XILINX_CONF:="${XILINX_PATH}/ISE/settings${XILINX_ARCH}.sh"}
XILEDK_CONF=${XILEDK_CONF:="${XILINX_PATH}/EDK/settings${XILINX_ARCH}.sh"}
PATH_ARCH=""
[ "$XILINX_ARCH" == "64" ] && PATH_ARCH=$XILINX_ARCH

if [ -r $XILINX_CONF ] ; then
	source $XILINX_CONF
else
	echo "Cannot find $XILINX_CONF!"
	exit 1
fi

if [ -r $XILEDK_CONF ] ; then
	source $XILEDK_CONF
#else
	#echo "Cannot find $XILEDK_CONF!"
	#exit 1
fi

# allow ISE/EDK to use the USB Cable Driver
# - no longer need this since 11.1?
#export XIL_IMPACT_USE_LIBUSB=1
# added to override usage of system's tcl library
# - no longer need this on slack13.0 (tcl8.5.7)
#export LD_PRELOAD=${XILINX}/lib/${PLATFORM}/libtcl8.4.so
# added to use xilinx usb jtag cable
USB_DRIVER="/home/share/tool/lib${PATH_ARCH}/libusb-driver.so"
[ -r "$USB_DRIVER" ] && export LD_PRELOAD="$LD_PRELOAD $USB_DRIVER"
# added to use digilent usb jtag cable
DIGILENT_PATH="/usr/lib${PATH_ARCH}/digilent/adept"
LIBUSB_PATH="/home/share/tool/lib${PATH_ARCH}/libusb1/lib"
[ -d $DIGILENT_PATH -a -d $LIBUSB_PATH ] &&
	LD_LIBRARY_PATH="$LIBUSB_PATH:$DIGILENT_PATH:$LD_LIBRARY_PATH"

THISPATH="$XILINX_PATH/EDK/gnu/microblaze/lin${PATH_ARCH}/bin"
THISPATH="$THISPATH:$XILINX_PATH/EDK/gnu/powerpc-eabi/lin${PATH_ARCH}/bin"
export PATH="$THISPATH:$PATH"

if [ "$1" == "" ] ; then
	# start a shell
	exec env PS1="(XIL-EXEC) \u@\h:\w$ " $(which bash)
else
	target=$1
	shift
	[ "$target" == "edk" ] && QT_PLUGIN_PATH= xps $@
	[ "$target" == "ise" ] && QT_PLUGIN_PATH= ise $@
	[ "$target" == "cgn" ] && QT_PLUGIN_PATH= coregen $@
	[ "$target" == "imp" ] && QT_PLUGIN_PATH= impact $@
	[ "$target" == "tcl" ] && QT_PLUGIN_PATH= xtclsh $@
fi

exit 0
